
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.formularioapp.backen.java.parser;

/** CUP generated class containing symbol constants. */
public class symPKM {
  /* terminals */
  public static final int NUMERO = 54;
  public static final int DESCRIPTION = 6;
  public static final int VALOR_FECHA = 45;
  public static final int TOTAL_PREGUNTAS = 8;
  public static final int MONO = 30;
  public static final int AUTO_CIERRE = 40;
  public static final int FECHA = 4;
  public static final int FONT = 16;
  public static final int IDENTIFICADOR = 50;
  public static final int HORIZONTAL = 36;
  public static final int IGUAL = 41;
  public static final int CIERRE_ETIQUETA = 39;
  public static final int COLORRGB = 48;
  public static final int TOTAL_SECCIONES = 7;
  public static final int CURSIVE = 32;
  public static final int SELECT = 28;
  public static final int VERTICAL = 35;
  public static final int BACKGROUND = 15;
  public static final int COLORHSL = 49;
  public static final int EOF = 0;
  public static final int SIZE = 19;
  public static final int TABLE = 23;
  public static final int COMILLA = 51;
  public static final int error = 1;
  public static final int COMA = 42;
  public static final int LINE = 24;
  public static final int MENOR = 37;
  public static final int LLAVE_ABRE = 43;
  public static final int MULTIPLE = 29;
  public static final int COLOR = 14;
  public static final int EMOJI = 53;
  public static final int MAYOR = 38;
  public static final int MULTIPLES = 12;
  public static final int SELECCION = 11;
  public static final int FAMILY = 17;
  public static final int CONTENT = 22;
  public static final int AUTHOR = 3;
  public static final int ELEMENT = 25;
  public static final int DROP = 27;
  public static final int SANS_SERIF = 31;
  public static final int METADATA_SEP = 2;
  public static final int OPEN = 26;
  public static final int BORDER = 20;
  public static final int LLAVE_CIERRA = 44;
  public static final int TEXT = 18;
  public static final int TEXTO = 52;
  public static final int ABIERTAS = 9;
  public static final int SECTION = 21;
  public static final int COLORHEX = 47;
  public static final int STYLE = 13;
  public static final int DESPLEGABLES = 10;
  public static final int VALOR_HORA = 46;
  public static final int HORA = 5;
  public static final int DOTTED = 33;
  public static final int DOUBLE_STYLE = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "METADATA_SEP",
  "AUTHOR",
  "FECHA",
  "HORA",
  "DESCRIPTION",
  "TOTAL_SECCIONES",
  "TOTAL_PREGUNTAS",
  "ABIERTAS",
  "DESPLEGABLES",
  "SELECCION",
  "MULTIPLES",
  "STYLE",
  "COLOR",
  "BACKGROUND",
  "FONT",
  "FAMILY",
  "TEXT",
  "SIZE",
  "BORDER",
  "SECTION",
  "CONTENT",
  "TABLE",
  "LINE",
  "ELEMENT",
  "OPEN",
  "DROP",
  "SELECT",
  "MULTIPLE",
  "MONO",
  "SANS_SERIF",
  "CURSIVE",
  "DOTTED",
  "DOUBLE_STYLE",
  "VERTICAL",
  "HORIZONTAL",
  "MENOR",
  "MAYOR",
  "CIERRE_ETIQUETA",
  "AUTO_CIERRE",
  "IGUAL",
  "COMA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "VALOR_FECHA",
  "VALOR_HORA",
  "COLORHEX",
  "COLORRGB",
  "COLORHSL",
  "IDENTIFICADOR",
  "COMILLA",
  "TEXTO",
  "EMOJI",
  "NUMERO"
  };
}

