
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

import java_cup.runtime.*;
import java.util.*;
import lexer.LexerPKM;
import pruebasintacticocompi.pruebasproyecto1.ErroresDeAnalizadores;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parserPKM extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return symPKM.class;
}

  /** Default constructor. */
  @Deprecated
  public parserPKM() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parserPKM(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserPKM(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\102\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\031\000\002\004\003\000\002\004\003" +
    "\000\002\027\005\000\002\027\004\000\002\030\004\000" +
    "\002\030\004\000\002\030\003\000\002\030\003\000\002" +
    "\005\011\000\002\006\004\000\002\006\003\000\002\007" +
    "\007\000\002\007\007\000\002\007\010\000\002\007\010" +
    "\000\002\007\015\000\002\034\003\000\002\034\003\000" +
    "\002\034\003\000\002\034\003\000\002\032\003\000\002" +
    "\032\003\000\002\032\003\000\002\033\003\000\002\033" +
    "\003\000\002\033\003\000\002\031\003\000\002\031\003" +
    "\000\002\010\004\000\002\010\003\000\002\011\003\000" +
    "\002\011\003\000\002\011\003\000\002\011\003\000\002" +
    "\011\003\000\002\011\003\000\002\011\003\000\002\012" +
    "\032\000\002\012\031\000\002\013\020\000\002\013\017" +
    "\000\002\014\004\000\002\014\003\000\002\015\011\000" +
    "\002\016\004\000\002\016\003\000\002\017\011\000\002" +
    "\020\013\000\002\020\017\000\002\021\013\000\002\021" +
    "\017\000\002\022\021\000\002\022\025\000\002\023\021" +
    "\000\002\023\025\000\002\024\023\000\002\024\027\000" +
    "\002\025\005\000\002\025\003\000\002\026\005\000\002" +
    "\026\003\000\002\026\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u0107\000\004\004\004\001\002\000\004\004\362\001" +
    "\002\000\006\002\uffff\047\011\001\002\000\004\002\007" +
    "\001\002\000\004\002\001\001\002\000\010\002\uffde\047" +
    "\uffde\051\uffde\001\002\000\020\024\023\027\024\031\025" +
    "\034\030\035\026\036\031\037\027\001\002\000\010\002" +
    "\uffd9\047\uffd9\051\uffd9\001\002\000\010\002\uffdb\047\uffdb" +
    "\051\uffdb\001\002\000\006\002\000\047\011\001\002\000" +
    "\010\002\uffe0\047\uffe0\051\uffe0\001\002\000\010\002\uffdf" +
    "\047\uffdf\051\uffdf\001\002\000\010\002\uffdd\047\uffdd\051" +
    "\uffdd\001\002\000\010\002\uffdc\047\uffdc\051\uffdc\001\002" +
    "\000\010\002\uffda\047\uffda\051\uffda\001\002\000\010\002" +
    "\uffe1\047\uffe1\051\uffe1\001\002\000\004\053\346\001\002" +
    "\000\004\053\304\001\002\000\004\050\234\001\002\000" +
    "\004\053\212\001\002\000\004\053\163\001\002\000\004" +
    "\053\147\001\002\000\004\053\032\001\002\000\004\070" +
    "\033\001\002\000\004\054\034\001\002\000\004\070\035" +
    "\001\002\000\004\054\036\001\002\000\004\065\040\001" +
    "\002\000\004\054\050\001\002\000\010\065\042\066\041" +
    "\067\043\001\002\000\010\065\ufff7\066\ufff7\067\ufff7\001" +
    "\002\000\016\006\ufffa\011\ufffa\050\ufffa\052\ufffa\054\ufffa" +
    "\056\ufffa\001\002\000\010\065\ufff6\066\ufff6\067\ufff6\001" +
    "\002\000\010\065\046\066\045\067\047\001\002\000\010" +
    "\065\ufff9\066\ufff9\067\ufff9\001\002\000\016\006\ufffb\011" +
    "\ufffb\050\ufffb\052\ufffb\054\ufffb\056\ufffb\001\002\000\010" +
    "\065\ufff8\066\ufff8\067\ufff8\001\002\000\004\055\051\001" +
    "\002\000\004\065\040\001\002\000\006\054\uffc3\056\uffc3" +
    "\001\002\000\006\054\054\056\055\001\002\000\004\065" +
    "\040\001\002\000\004\054\056\001\002\000\004\070\057" +
    "\001\002\000\006\050\061\052\060\001\002\000\010\002" +
    "\uffc8\047\uffc8\051\uffc8\001\002\000\004\047\062\001\002" +
    "\000\004\017\067\001\002\000\004\051\064\001\002\000" +
    "\004\036\065\001\002\000\004\050\066\001\002\000\010" +
    "\002\uffc7\047\uffc7\051\uffc7\001\002\000\004\050\070\001" +
    "\002\000\004\047\073\001\002\000\006\047\ufff3\051\ufff3" +
    "\001\002\000\006\047\073\051\143\001\002\000\014\020" +
    "\075\021\100\022\077\024\076\026\074\001\002\000\004" +
    "\054\126\001\002\000\004\053\123\001\002\000\004\025" +
    "\117\001\002\000\004\023\110\001\002\000\004\053\101" +
    "\001\002\000\012\061\103\062\102\063\105\064\104\001" +
    "\002\000\004\052\uffec\001\002\000\004\052\uffed\001\002" +
    "\000\004\052\uffea\001\002\000\004\052\uffeb\001\002\000" +
    "\004\052\107\001\002\000\006\047\ufff1\051\ufff1\001\002" +
    "\000\004\053\111\001\002\000\010\040\112\041\115\042" +
    "\113\001\002\000\004\052\uffe9\001\002\000\004\052\uffe7" +
    "\001\002\000\004\052\116\001\002\000\004\052\uffe8\001" +
    "\002\000\006\047\ufff0\051\ufff0\001\002\000\004\053\120" +
    "\001\002\000\004\070\121\001\002\000\004\052\122\001" +
    "\002\000\006\047\uffef\051\uffef\001\002\000\012\061\103" +
    "\062\102\063\105\064\104\001\002\000\004\052\125\001" +
    "\002\000\006\047\ufff2\051\ufff2\001\002\000\004\070\127" +
    "\001\002\000\004\054\130\001\002\000\010\032\132\043" +
    "\133\044\134\001\002\000\004\054\135\001\002\000\004" +
    "\054\uffe6\001\002\000\004\054\uffe5\001\002\000\004\054" +
    "\uffe4\001\002\000\004\020\136\001\002\000\004\053\137" +
    "\001\002\000\012\061\103\062\102\063\105\064\104\001" +
    "\002\000\004\052\141\001\002\000\006\047\uffee\051\uffee" +
    "\001\002\000\006\047\ufff4\051\ufff4\001\002\000\004\017" +
    "\144\001\002\000\004\050\145\001\002\000\006\047\ufff5" +
    "\051\ufff5\001\002\000\006\054\uffc4\056\uffc4\001\002\000" +
    "\004\070\150\001\002\000\004\054\151\001\002\000\004" +
    "\070\152\001\002\000\004\054\153\001\002\000\004\065" +
    "\040\001\002\000\006\050\156\052\155\001\002\000\010" +
    "\002\uffcc\047\uffcc\051\uffcc\001\002\000\004\047\062\001" +
    "\002\000\004\051\160\001\002\000\004\034\161\001\002" +
    "\000\004\050\162\001\002\000\010\002\uffcb\047\uffcb\051" +
    "\uffcb\001\002\000\004\070\164\001\002\000\004\054\165" +
    "\001\002\000\004\070\166\001\002\000\004\054\167\001" +
    "\002\000\004\065\040\001\002\000\004\054\171\001\002" +
    "\000\004\055\172\001\002\000\004\065\040\001\002\000" +
    "\006\054\054\056\174\001\002\000\004\054\175\001\002" +
    "\000\004\055\176\001\002\000\010\054\uffc0\056\uffc0\070" +
    "\177\001\002\000\006\054\uffc1\056\uffc1\001\002\000\006" +
    "\054\201\056\202\001\002\000\004\070\211\001\002\000" +
    "\006\050\204\052\203\001\002\000\010\002\uffc6\047\uffc6" +
    "\051\uffc6\001\002\000\004\047\062\001\002\000\004\051" +
    "\206\001\002\000\004\037\207\001\002\000\004\050\210" +
    "\001\002\000\010\002\uffc5\047\uffc5\051\uffc5\001\002\000" +
    "\006\054\uffc2\056\uffc2\001\002\000\004\070\213\001\002" +
    "\000\004\054\214\001\002\000\004\070\215\001\002\000" +
    "\004\054\216\001\002\000\004\065\040\001\002\000\004" +
    "\054\220\001\002\000\004\055\221\001\002\000\004\065" +
    "\040\001\002\000\006\054\054\056\223\001\002\000\004" +
    "\054\224\001\002\000\004\070\225\001\002\000\006\050" +
    "\227\052\226\001\002\000\010\002\uffca\047\uffca\051\uffca" +
    "\001\002\000\004\047\062\001\002\000\004\051\231\001" +
    "\002\000\004\035\232\001\002\000\004\050\233\001\002" +
    "\000\010\002\uffc9\047\uffc9\051\uffc9\001\002\000\004\047" +
    "\235\001\002\000\006\017\067\030\273\001\002\000\004" +
    "\047\237\001\002\000\004\030\240\001\002\000\004\050" +
    "\241\001\002\000\004\047\243\001\002\000\006\047\243" +
    "\051\265\001\002\000\004\032\245\001\002\000\006\047" +
    "\uffd3\051\uffd3\001\002\000\004\050\246\001\002\000\004" +
    "\047\251\001\002\000\006\047\251\051\261\001\002\000" +
    "\006\047\uffd0\051\uffd0\001\002\000\004\033\252\001\002" +
    "\000\004\050\253\001\002\000\004\047\011\001\002\000" +
    "\006\047\011\051\255\001\002\000\004\033\256\001\002" +
    "\000\004\050\257\001\002\000\006\047\uffcf\051\uffcf\001" +
    "\002\000\006\047\uffd1\051\uffd1\001\002\000\004\032\262" +
    "\001\002\000\004\050\263\001\002\000\006\047\uffd2\051" +
    "\uffd2\001\002\000\006\047\uffd4\051\uffd4\001\002\000\004" +
    "\030\266\001\002\000\004\050\267\001\002\000\004\051" +
    "\270\001\002\000\004\031\271\001\002\000\004\050\272" +
    "\001\002\000\010\002\uffd6\047\uffd6\051\uffd6\001\002\000" +
    "\004\050\274\001\002\000\004\047\243\001\002\000\006" +
    "\047\243\051\276\001\002\000\004\030\277\001\002\000" +
    "\004\050\300\001\002\000\004\051\301\001\002\000\004" +
    "\031\302\001\002\000\004\050\303\001\002\000\010\002" +
    "\uffd5\047\uffd5\051\uffd5\001\002\000\004\070\305\001\002" +
    "\000\004\054\306\001\002\000\004\070\307\001\002\000" +
    "\004\054\310\001\002\000\004\070\311\001\002\000\004" +
    "\054\312\001\002\000\004\070\313\001\002\000\004\054" +
    "\314\001\002\000\006\045\317\046\315\001\002\000\004" +
    "\050\uffe2\001\002\000\004\050\320\001\002\000\004\050" +
    "\uffe3\001\002\000\004\047\322\001\002\000\004\047\334" +
    "\001\002\000\006\017\067\030\323\001\002\000\004\050" +
    "\324\001\002\000\004\047\011\001\002\000\006\047\011" +
    "\051\326\001\002\000\004\030\327\001\002\000\004\050" +
    "\330\001\002\000\004\051\331\001\002\000\004\027\332" +
    "\001\002\000\004\050\333\001\002\000\010\002\uffd7\047" +
    "\uffd7\051\uffd7\001\002\000\004\030\335\001\002\000\004" +
    "\050\336\001\002\000\004\047\011\001\002\000\006\047" +
    "\011\051\340\001\002\000\004\030\341\001\002\000\004" +
    "\050\342\001\002\000\004\051\343\001\002\000\004\027" +
    "\344\001\002\000\004\050\345\001\002\000\010\002\uffd8" +
    "\047\uffd8\051\uffd8\001\002\000\004\070\347\001\002\000" +
    "\004\054\350\001\002\000\004\070\351\001\002\000\004" +
    "\054\352\001\002\000\004\065\040\001\002\000\006\050" +
    "\355\052\354\001\002\000\010\002\uffce\047\uffce\051\uffce" +
    "\001\002\000\004\047\062\001\002\000\004\051\357\001" +
    "\002\000\004\024\360\001\002\000\004\050\361\001\002" +
    "\000\010\002\uffcd\047\uffcd\051\uffcd\001\002\000\004\005" +
    "\363\001\002\000\006\064\365\065\040\001\002\000\004" +
    "\006\ufffd\001\002\000\004\006\ufffc\001\002\000\004\006" +
    "\367\001\002\000\004\057\370\001\002\000\004\007\371" +
    "\001\002\000\004\060\372\001\002\000\004\010\373\001" +
    "\002\000\004\065\040\001\002\000\004\011\375\001\002" +
    "\000\004\070\376\001\002\000\004\012\377\001\002\000" +
    "\004\070\u0100\001\002\000\004\013\u0101\001\002\000\004" +
    "\070\u0102\001\002\000\004\014\u0103\001\002\000\004\070" +
    "\u0104\001\002\000\004\015\u0105\001\002\000\004\070\u0106" +
    "\001\002\000\004\016\u0107\001\002\000\004\070\u0108\001" +
    "\002\000\004\004\u0109\001\002\000\006\002\ufffe\047\ufffe" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u0107\000\006\002\005\003\004\001\001\000\002\001" +
    "\001\000\024\010\013\011\014\012\015\013\007\020\016" +
    "\021\017\022\012\023\020\024\011\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\011\021\012" +
    "\015\013\007\020\016\021\017\022\012\023\020\024\011" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\027\036\001\001\000\002" +
    "\001\001\000\004\030\043\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\025\052\027\051\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\027\145\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\005\062\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\006\071\007\070\001\001\000" +
    "\002\001\001\000\004\007\141\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\034\105\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\032\113\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\034\123\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\033\130\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\034\137\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\027\153\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\156\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\027\167\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\025\172\027\051\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\026\177\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\204\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\027\216\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\025\221\027\051\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\227\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\005\235\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\014\241" +
    "\015\243\001\001\000\004\015\263\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\016\246" +
    "\017\247\001\001\000\004\017\257\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\024\010\253" +
    "\011\014\012\015\013\007\020\016\021\017\022\012\023" +
    "\020\024\011\001\001\000\022\011\021\012\015\013\007" +
    "\020\016\021\017\022\012\023\020\024\011\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\014\274\015\243" +
    "\001\001\000\004\015\263\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\031\315\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\320\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\024\010\324" +
    "\011\014\012\015\013\007\020\016\021\017\022\012\023" +
    "\020\024\011\001\001\000\022\011\021\012\015\013\007" +
    "\020\016\021\017\022\012\023\020\024\011\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\024\010\336\011\014\012\015" +
    "\013\007\020\016\021\017\022\012\023\020\024\011\001" +
    "\001\000\022\011\021\012\015\013\007\020\016\021\017" +
    "\022\012\023\020\024\011\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\027\352" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\355\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\004" +
    "\365\027\363\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\027\373\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserPKM$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserPKM$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserPKM$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    LexerPKM lexer;
    private List<ErroresDeAnalizadores> errores = new ArrayList<>();

    public parserPKM(LexerPKM lexer){
        super(lexer);
        this.lexer = lexer;
    }

    public List<ErroresDeAnalizadores> getErrores(){
        return errores;
    }

    @Override
    public void syntax_error(Symbol s){
        String lex;

        if (s.value != null) {
            lex = s.value.toString();
        } else {
            try {
                lex = symbl_name_from_id(s.sym);
            } catch (Exception e) {
                lex = "TOKEN_" + s.sym;
            }
        }

        errores.add(new ErroresDeAnalizadores(
            lex + " -> error sintáctico",
            "Sintáctico",
            "PKM",
            s.left,
            s.right
        ));
    }

    @Override
    public void unrecovered_syntax_error(Symbol s){
        String lex;

        if (s.value != null) {
            lex = s.value.toString();
        } else {
            try {
                lex = symbl_name_from_id(s.sym);
            } catch (Exception e) {
                lex = "TOKEN_" + s.sym;
            }
        }

        errores.add(new ErroresDeAnalizadores(
            lex + " -> error sintáctico irrecuperable",
            "Sintáctico",
            "PKM",
            s.left,
            s.right
        ));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parserPKM$actions {
  private final parserPKM parser;

  /** Constructor */
  CUP$parserPKM$actions(parserPKM parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parserPKM$do_action_part00000000(
    int                        CUP$parserPKM$act_num,
    java_cup.runtime.lr_parser CUP$parserPKM$parser,
    java.util.Stack            CUP$parserPKM$stack,
    int                        CUP$parserPKM$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserPKM$result;

      /* select the action based on the action number */
      switch (CUP$parserPKM$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).value;
		RESULT = start_val;
              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserPKM$parser.done_parsing();
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= metadatos lista_elementos 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= metadatos 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // metadatos ::= METADATA_SEP METADATA_SEP AUTHOR valor_autor FECHA VALOR_FECHA HORA VALOR_HORA DESCRIPTION cadena TOTAL_SECCIONES NUMERO TOTAL_PREGUNTAS NUMERO ABIERTAS NUMERO DESPLEGABLES NUMERO SELECCION NUMERO MULTIPLES NUMERO METADATA_SEP 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("metadatos",1, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-22)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // valor_autor ::= cadena 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("valor_autor",2, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // valor_autor ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("valor_autor",2, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // cadena ::= COMILLA contenido COMILLA 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).value;
		 RESULT = c; 
              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("cadena",21, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // cadena ::= COMILLA COMILLA 
            {
              String RESULT =null;
		 RESULT = ""; 
              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("cadena",21, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // contenido ::= contenido TEXTO 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parserPKM$stack.peek()).value;
		 RESULT = c + t.toString(); 
              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("contenido",22, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // contenido ::= contenido EMOJI 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parserPKM$stack.peek()).value;
		 RESULT = c + e.toString(); 
              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("contenido",22, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // contenido ::= TEXTO 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parserPKM$stack.peek()).value;
		 RESULT = t.toString(); 
              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("contenido",22, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // contenido ::= EMOJI 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$parserPKM$stack.peek()).value;
		 RESULT = e.toString(); 
              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("contenido",22, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // estilos_bloque ::= MENOR STYLE MAYOR lista_atributos CIERRE_ETIQUETA STYLE MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("estilos_bloque",3, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // lista_atributos ::= lista_atributos atributo 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_atributos",4, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // lista_atributos ::= atributo 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_atributos",4, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // atributo ::= MENOR COLOR IGUAL color_val AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-4)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // atributo ::= MENOR BACKGROUND IGUAL color_val AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-4)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // atributo ::= MENOR FONT FAMILY IGUAL tipo_fuente AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-5)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // atributo ::= MENOR TEXT SIZE IGUAL NUMERO AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-5)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // atributo ::= MENOR BORDER COMA NUMERO COMA tipo_borde COMA COLOR IGUAL color_val AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-10)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // color_val ::= COLORHEX 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("color_val",26, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // color_val ::= COLORRGB 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("color_val",26, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // color_val ::= COLORHSL 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("color_val",26, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // color_val ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("color_val",26, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo_fuente ::= MONO 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("tipo_fuente",24, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo_fuente ::= SANS_SERIF 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("tipo_fuente",24, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo_fuente ::= CURSIVE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("tipo_fuente",24, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo_borde ::= LINE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("tipo_borde",25, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipo_borde ::= DOTTED 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("tipo_borde",25, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipo_borde ::= DOUBLE_STYLE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("tipo_borde",25, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // orientacion ::= VERTICAL 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("orientacion",23, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // orientacion ::= HORIZONTAL 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("orientacion",23, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // lista_elementos ::= lista_elementos elemento 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_elementos",6, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_elementos ::= elemento 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_elementos",6, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // elemento ::= seccion 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("elemento",7, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // elemento ::= tabla 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("elemento",7, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // elemento ::= texto 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("elemento",7, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // elemento ::= open_q 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("elemento",7, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // elemento ::= drop_q 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("elemento",7, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // elemento ::= select_q 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("elemento",7, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // elemento ::= multiple_q 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("elemento",7, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // seccion ::= MENOR SECTION IGUAL NUMERO COMA NUMERO COMA NUMERO COMA NUMERO COMA orientacion MAYOR estilos_bloque MENOR CONTENT MAYOR lista_elementos CIERRE_ETIQUETA CONTENT MAYOR CIERRE_ETIQUETA SECTION MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("seccion",8, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-23)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // seccion ::= MENOR SECTION IGUAL NUMERO COMA NUMERO COMA NUMERO COMA NUMERO COMA orientacion MAYOR MENOR CONTENT MAYOR lista_elementos CIERRE_ETIQUETA CONTENT MAYOR CIERRE_ETIQUETA SECTION MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("seccion",8, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-22)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // tabla ::= MENOR TABLE MAYOR estilos_bloque MENOR CONTENT MAYOR lista_lineas CIERRE_ETIQUETA CONTENT MAYOR CIERRE_ETIQUETA TABLE MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("tabla",9, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-13)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // tabla ::= MENOR TABLE MAYOR MENOR CONTENT MAYOR lista_lineas CIERRE_ETIQUETA CONTENT MAYOR CIERRE_ETIQUETA TABLE MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("tabla",9, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-12)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // lista_lineas ::= lista_lineas linea 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_lineas",10, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // lista_lineas ::= linea 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_lineas",10, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // linea ::= MENOR LINE MAYOR lista_celdas CIERRE_ETIQUETA LINE MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("linea",11, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // lista_celdas ::= lista_celdas celda 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_celdas",12, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // lista_celdas ::= celda 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_celdas",12, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // celda ::= MENOR ELEMENT MAYOR lista_elementos CIERRE_ETIQUETA ELEMENT MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("celda",13, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // texto ::= MENOR TEXT IGUAL NUMERO COMA NUMERO COMA cadena AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("texto",14, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-8)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // texto ::= MENOR TEXT IGUAL NUMERO COMA NUMERO COMA cadena MAYOR estilos_bloque CIERRE_ETIQUETA TEXT MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("texto",14, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-12)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // open_q ::= MENOR OPEN IGUAL NUMERO COMA NUMERO COMA cadena AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("open_q",15, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-8)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // open_q ::= MENOR OPEN IGUAL NUMERO COMA NUMERO COMA cadena MAYOR estilos_bloque CIERRE_ETIQUETA OPEN MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("open_q",15, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-12)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // drop_q ::= MENOR DROP IGUAL NUMERO COMA NUMERO COMA cadena COMA LLAVE_ABRE lista_opciones LLAVE_CIERRA COMA NUMERO AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("drop_q",16, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-14)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // drop_q ::= MENOR DROP IGUAL NUMERO COMA NUMERO COMA cadena COMA LLAVE_ABRE lista_opciones LLAVE_CIERRA COMA NUMERO MAYOR estilos_bloque CIERRE_ETIQUETA DROP MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("drop_q",16, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-18)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // select_q ::= MENOR SELECT IGUAL NUMERO COMA NUMERO COMA cadena COMA LLAVE_ABRE lista_opciones LLAVE_CIERRA COMA NUMERO AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("select_q",17, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-14)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // select_q ::= MENOR SELECT IGUAL NUMERO COMA NUMERO COMA cadena COMA LLAVE_ABRE lista_opciones LLAVE_CIERRA COMA NUMERO MAYOR estilos_bloque CIERRE_ETIQUETA SELECT MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("select_q",17, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-18)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // multiple_q ::= MENOR MULTIPLE IGUAL NUMERO COMA NUMERO COMA cadena COMA LLAVE_ABRE lista_opciones LLAVE_CIERRA COMA LLAVE_ABRE lista_nums LLAVE_CIERRA AUTO_CIERRE 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("multiple_q",18, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-16)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // multiple_q ::= MENOR MULTIPLE IGUAL NUMERO COMA NUMERO COMA cadena COMA LLAVE_ABRE lista_opciones LLAVE_CIERRA COMA LLAVE_ABRE lista_nums LLAVE_CIERRA MAYOR estilos_bloque CIERRE_ETIQUETA MULTIPLE MAYOR 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("multiple_q",18, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-20)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // lista_opciones ::= lista_opciones COMA cadena 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_opciones",19, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // lista_opciones ::= cadena 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_opciones",19, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // lista_nums ::= lista_nums COMA NUMERO 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_nums",20, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.elementAt(CUP$parserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // lista_nums ::= NUMERO 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_nums",20, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // lista_nums ::= 
            {
              Object RESULT =null;

              CUP$parserPKM$result = parser.getSymbolFactory().newSymbol("lista_nums",20, ((java_cup.runtime.Symbol)CUP$parserPKM$stack.peek()), RESULT);
            }
          return CUP$parserPKM$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parserPKM$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parserPKM$do_action(
    int                        CUP$parserPKM$act_num,
    java_cup.runtime.lr_parser CUP$parserPKM$parser,
    java.util.Stack            CUP$parserPKM$stack,
    int                        CUP$parserPKM$top)
    throws java.lang.Exception
    {
              return CUP$parserPKM$do_action_part00000000(
                               CUP$parserPKM$act_num,
                               CUP$parserPKM$parser,
                               CUP$parserPKM$stack,
                               CUP$parserPKM$top);
    }
}

}
