
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

import java.util.List;
import java.util.ArrayList;
import pruebasintacticocompi.pruebasproyecto1.ErroresDeAnalizadores;
import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\142\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\004\000\002\004\004" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\007\003\000\002\007\003\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\007\003\000\002\005" +
    "\004\000\002\005\006\000\002\006\005\000\002\010\003" +
    "\000\002\011\005\000\002\011\005\000\002\011\004\000" +
    "\002\011\003\000\002\012\005\000\002\012\005\000\002" +
    "\012\005\000\002\012\005\000\002\012\005\000\002\012" +
    "\005\000\002\012\003\000\002\013\005\000\002\013\005" +
    "\000\002\013\003\000\002\014\005\000\002\014\005\000" +
    "\002\014\005\000\002\014\003\000\002\015\005\000\002" +
    "\015\003\000\002\015\003\000\002\015\003\000\002\015" +
    "\005\000\002\015\005\000\002\016\006\000\002\017\004" +
    "\000\002\017\003\000\002\020\005\000\002\020\005\000" +
    "\002\021\004\000\002\021\005\000\002\022\003\000\002" +
    "\022\003\000\002\022\003\000\002\022\003\000\002\023" +
    "\005\000\002\023\003\000\002\024\003\000\002\024\003" +
    "\000\002\024\003\000\002\025\007\000\002\026\003\000" +
    "\002\026\003\000\002\026\003\000\002\026\003\000\002" +
    "\027\007\000\002\030\007\000\002\031\005\000\002\032" +
    "\005\000\002\033\004\000\002\033\003\000\002\034\003" +
    "\000\002\034\003\000\002\034\003\000\002\035\012\000" +
    "\002\036\004\000\002\036\006\000\002\036\002\000\002" +
    "\037\003\000\002\037\003\000\002\037\003\000\002\040" +
    "\011\000\002\041\012\000\002\042\015\000\002\042\015" +
    "\000\002\043\003\000\002\043\003\000\002\043\003\000" +
    "\002\043\003\000\002\043\003\000\002\043\003\000\002" +
    "\043\003\000\002\043\003\000\002\043\003\000\002\043" +
    "\003\000\002\043\003\000\002\043\003\000\002\043\003" +
    "\000\002\043\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\277\000\032\004\007\005\022\006\033\007\014\031" +
    "\013\033\011\034\017\035\031\041\004\042\023\043\024" +
    "\122\027\001\002\000\004\122\ufff5\001\002\000\036\002" +
    "\uffb4\004\uffb4\005\uffb4\006\uffb4\007\uffb4\031\uffb4\033\uffb4" +
    "\034\uffb4\035\uffb4\041\uffb4\042\uffb4\043\uffb4\105\uffb4\122" +
    "\uffb4\001\002\000\034\002\000\004\007\005\022\006\033" +
    "\007\014\031\013\033\011\034\017\035\031\041\004\042" +
    "\023\043\024\122\027\001\002\000\004\122\ufff8\001\002" +
    "\000\004\122\276\001\002\000\004\102\270\001\002\000" +
    "\034\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa\031\ufffa" +
    "\033\ufffa\034\ufffa\035\ufffa\041\ufffa\042\ufffa\043\ufffa\122" +
    "\ufffa\001\002\000\004\102\254\001\002\000\004\106\153" +
    "\001\002\000\004\112\152\001\002\000\004\002\151\001" +
    "\002\000\004\104\142\001\002\000\036\002\uffb3\004\uffb3" +
    "\005\uffb3\006\uffb3\007\uffb3\031\uffb3\033\uffb3\034\uffb3\035" +
    "\uffb3\041\uffb3\042\uffb3\043\uffb3\105\uffb3\122\uffb3\001\002" +
    "\000\004\112\141\001\002\000\004\122\ufff7\001\002\000" +
    "\004\122\ufff4\001\002\000\004\122\ufff3\001\002\000\034" +
    "\002\ufffe\004\ufffe\005\ufffe\006\ufffe\007\ufffe\031\ufffe\033" +
    "\ufffe\034\ufffe\035\ufffe\041\ufffe\042\ufffe\043\ufffe\122\ufffe" +
    "\001\002\000\036\002\uffb2\004\uffb2\005\uffb2\006\uffb2\007" +
    "\uffb2\031\uffb2\033\uffb2\034\uffb2\035\uffb2\041\uffb2\042\uffb2" +
    "\043\uffb2\105\uffb2\122\uffb2\001\002\000\004\075\130\001" +
    "\002\000\034\002\ufffb\004\ufffb\005\ufffb\006\ufffb\007\ufffb" +
    "\031\ufffb\033\ufffb\034\ufffb\035\ufffb\041\ufffb\042\ufffb\043" +
    "\ufffb\122\ufffb\001\002\000\004\102\034\001\002\000\034" +
    "\002\ufff9\004\ufff9\005\ufff9\006\ufff9\007\ufff9\031\ufff9\033" +
    "\ufff9\034\ufff9\035\ufff9\041\ufff9\042\ufff9\043\ufff9\122\ufff9" +
    "\001\002\000\004\122\ufff6\001\002\000\004\122\035\001" +
    "\002\000\006\036\127\075\130\001\002\000\004\112\037" +
    "\001\002\000\014\100\051\102\044\120\043\121\040\122" +
    "\052\001\002\000\044\061\uffda\062\uffda\063\uffda\064\uffda" +
    "\065\uffda\066\uffda\067\uffda\070\uffda\071\uffda\072\uffda\073" +
    "\uffda\074\uffda\076\uffda\077\uffda\103\uffda\112\uffda\114\uffda" +
    "\001\002\000\012\076\055\077\054\103\uffef\112\uffef\001" +
    "\002\000\040\061\uffe1\062\uffe1\063\102\064\104\066\103" +
    "\067\uffe1\070\uffe1\071\uffe1\072\uffe1\073\uffe1\074\uffe1\076" +
    "\uffe1\077\uffe1\103\uffe1\112\uffe1\001\002\000\044\061\uffdb" +
    "\062\uffdb\063\uffdb\064\uffdb\065\uffdb\066\uffdb\067\uffdb\070" +
    "\uffdb\071\uffdb\072\uffdb\073\uffdb\074\uffdb\076\uffdb\077\uffdb" +
    "\103\uffdb\112\uffdb\114\uffdb\001\002\000\014\100\051\102" +
    "\044\120\043\121\040\122\052\001\002\000\004\112\112" +
    "\001\002\000\032\061\066\062\064\067\071\070\070\071" +
    "\073\072\072\073\065\074\067\076\uffe4\077\uffe4\103\uffe4" +
    "\112\uffe4\001\002\000\012\076\uffeb\077\uffeb\103\uffeb\112" +
    "\uffeb\001\002\000\044\061\uffdd\062\uffdd\063\uffdd\064\uffdd" +
    "\065\061\066\uffdd\067\uffdd\070\uffdd\071\uffdd\072\uffdd\073" +
    "\uffdd\074\uffdd\076\uffdd\077\uffdd\103\uffdd\112\uffdd\114\060" +
    "\001\002\000\014\100\051\102\044\120\043\121\040\122" +
    "\052\001\002\000\044\061\uffd9\062\uffd9\063\uffd9\064\uffd9" +
    "\065\uffd9\066\uffd9\067\uffd9\070\uffd9\071\uffd9\072\uffd9\073" +
    "\uffd9\074\uffd9\076\uffd9\077\uffd9\103\uffd9\112\uffd9\114\uffd9" +
    "\001\002\000\012\076\uffec\077\uffec\103\uffec\112\uffec\001" +
    "\002\000\014\100\051\102\044\120\043\121\040\122\052" +
    "\001\002\000\014\100\051\102\044\120\043\121\040\122" +
    "\052\001\002\000\012\076\uffee\077\uffee\103\uffee\112\uffee" +
    "\001\002\000\012\076\uffed\077\uffed\103\uffed\112\uffed\001" +
    "\002\000\004\122\063\001\002\000\012\102\044\120\043" +
    "\121\040\122\052\001\002\000\044\061\uffdc\062\uffdc\063" +
    "\uffdc\064\uffdc\065\061\066\uffdc\067\uffdc\070\uffdc\071\uffdc" +
    "\072\uffdc\073\uffdc\074\uffdc\076\uffdc\077\uffdc\103\uffdc\112" +
    "\uffdc\114\uffdc\001\002\000\044\061\uffd7\062\uffd7\063\uffd7" +
    "\064\uffd7\065\uffd7\066\uffd7\067\uffd7\070\uffd7\071\uffd7\072" +
    "\uffd7\073\uffd7\074\uffd7\076\uffd7\077\uffd7\103\uffd7\112\uffd7" +
    "\114\uffd7\001\002\000\012\102\044\120\043\121\040\122" +
    "\052\001\002\000\012\102\044\120\043\121\040\122\052" +
    "\001\002\000\012\102\044\120\043\121\040\122\052\001" +
    "\002\000\012\102\044\120\043\121\040\122\052\001\002" +
    "\000\012\102\044\120\043\121\040\122\052\001\002\000" +
    "\012\102\044\120\043\121\040\122\052\001\002\000\012" +
    "\102\044\120\043\121\040\122\052\001\002\000\012\102" +
    "\044\120\043\121\040\122\052\001\002\000\016\061\066" +
    "\062\064\076\uffe8\077\uffe8\103\uffe8\112\uffe8\001\002\000" +
    "\016\061\066\062\064\076\uffe7\077\uffe7\103\uffe7\112\uffe7" +
    "\001\002\000\016\061\066\062\064\076\uffea\077\uffea\103" +
    "\uffea\112\uffea\001\002\000\016\061\066\062\064\076\uffe9" +
    "\077\uffe9\103\uffe9\112\uffe9\001\002\000\016\061\066\062" +
    "\064\076\uffe5\077\uffe5\103\uffe5\112\uffe5\001\002\000\040" +
    "\061\uffe3\062\uffe3\063\102\064\104\066\103\067\uffe3\070" +
    "\uffe3\071\uffe3\072\uffe3\073\uffe3\074\uffe3\076\uffe3\077\uffe3" +
    "\103\uffe3\112\uffe3\001\002\000\012\102\044\120\043\121" +
    "\040\122\052\001\002\000\012\102\044\120\043\121\040" +
    "\122\052\001\002\000\012\102\044\120\043\121\040\122" +
    "\052\001\002\000\044\061\uffdf\062\uffdf\063\uffdf\064\uffdf" +
    "\065\061\066\uffdf\067\uffdf\070\uffdf\071\uffdf\072\uffdf\073" +
    "\uffdf\074\uffdf\076\uffdf\077\uffdf\103\uffdf\112\uffdf\114\060" +
    "\001\002\000\044\061\uffde\062\uffde\063\uffde\064\uffde\065" +
    "\061\066\uffde\067\uffde\070\uffde\071\uffde\072\uffde\073\uffde" +
    "\074\uffde\076\uffde\077\uffde\103\uffde\112\uffde\114\060\001" +
    "\002\000\044\061\uffe0\062\uffe0\063\uffe0\064\uffe0\065\061" +
    "\066\uffe0\067\uffe0\070\uffe0\071\uffe0\072\uffe0\073\uffe0\074" +
    "\uffe0\076\uffe0\077\uffe0\103\uffe0\112\uffe0\114\060\001\002" +
    "\000\016\061\066\062\064\076\uffe6\077\uffe6\103\uffe6\112" +
    "\uffe6\001\002\000\040\061\uffe2\062\uffe2\063\102\064\104" +
    "\066\103\067\uffe2\070\uffe2\071\uffe2\072\uffe2\073\uffe2\074" +
    "\uffe2\076\uffe2\077\uffe2\103\uffe2\112\uffe2\001\002\000\004" +
    "\122\027\001\002\000\004\103\114\001\002\000\004\104" +
    "\115\001\002\000\014\007\014\031\013\033\011\034\017" +
    "\035\031\001\002\000\016\007\uffbb\031\uffbb\033\uffbb\034" +
    "\uffbb\035\uffbb\105\uffbb\001\002\000\016\007\uffbc\031\uffbc" +
    "\033\uffbc\034\uffbc\035\uffbc\105\uffbc\001\002\000\016\007" +
    "\uffb9\031\uffb9\033\uffb9\034\uffb9\035\uffb9\105\uffb9\001\002" +
    "\000\016\007\uffba\031\uffba\033\uffba\034\uffba\035\uffba\105" +
    "\uffba\001\002\000\016\007\014\031\013\033\011\034\017" +
    "\035\031\105\124\001\002\000\016\007\uffbd\031\uffbd\033" +
    "\uffbd\034\uffbd\035\uffbd\105\uffbd\001\002\000\036\002\uffaf" +
    "\004\uffaf\005\uffaf\006\uffaf\007\uffaf\031\uffaf\033\uffaf\034" +
    "\uffaf\035\uffaf\041\uffaf\042\uffaf\043\uffaf\105\uffaf\122\uffaf" +
    "\001\002\000\004\103\126\001\002\000\044\061\uffd8\062" +
    "\uffd8\063\uffd8\064\uffd8\065\uffd8\066\uffd8\067\uffd8\070\uffd8" +
    "\071\uffd8\072\uffd8\073\uffd8\074\uffd8\076\uffd8\077\uffd8\103" +
    "\uffd8\112\uffd8\114\uffd8\001\002\000\004\120\132\001\002" +
    "\000\014\100\051\102\044\120\043\121\040\122\052\001" +
    "\002\000\006\103\ufff0\112\ufff0\001\002\000\004\113\133" +
    "\001\002\000\004\120\134\001\002\000\004\103\135\001" +
    "\002\000\004\104\136\001\002\000\014\007\014\031\013" +
    "\033\011\034\017\035\031\001\002\000\016\007\014\031" +
    "\013\033\011\034\017\035\031\105\140\001\002\000\036" +
    "\002\uffae\004\uffae\005\uffae\006\uffae\007\uffae\031\uffae\033" +
    "\uffae\034\uffae\035\uffae\041\uffae\042\uffae\043\uffae\105\uffae" +
    "\122\uffae\001\002\000\034\002\ufffd\004\ufffd\005\ufffd\006" +
    "\ufffd\007\ufffd\031\ufffd\033\ufffd\034\ufffd\035\ufffd\041\ufffd" +
    "\042\ufffd\043\ufffd\122\ufffd\001\002\000\014\007\014\031" +
    "\013\033\011\034\017\035\031\001\002\000\016\007\014" +
    "\031\013\033\011\034\017\035\031\105\144\001\002\000" +
    "\004\033\145\001\002\000\004\102\146\001\002\000\014" +
    "\100\051\102\044\120\043\121\040\122\052\001\002\000" +
    "\004\103\150\001\002\000\036\002\uffb0\004\uffb0\005\uffb0" +
    "\006\uffb0\007\uffb0\031\uffb0\033\uffb0\034\uffb0\035\uffb0\041" +
    "\uffb0\042\uffb0\043\uffb0\105\uffb0\122\uffb0\001\002\000\004" +
    "\002\001\001\002\000\034\002\ufffc\004\ufffc\005\ufffc\006" +
    "\ufffc\007\ufffc\031\ufffc\033\ufffc\034\ufffc\035\ufffc\041\ufffc" +
    "\042\ufffc\043\ufffc\122\ufffc\001\002\000\006\057\157\122" +
    "\156\001\002\000\010\057\uffd4\107\uffd4\122\uffd4\001\002" +
    "\000\010\057\157\107\253\122\156\001\002\000\004\111" +
    "\250\001\002\000\004\111\160\001\002\000\046\037\176" +
    "\040\204\044\200\045\172\046\203\047\202\050\165\051" +
    "\170\052\173\053\164\054\167\055\174\056\166\104\163" +
    "\120\201\123\205\124\175\125\161\001\002\000\004\112" +
    "\uffa3\001\002\000\010\057\uffd2\107\uffd2\122\uffd2\001\002" +
    "\000\016\007\014\011\222\012\216\013\221\014\220\015" +
    "\207\001\002\000\004\112\uffa9\001\002\000\004\112\uffac" +
    "\001\002\000\004\112\uffa6\001\002\000\004\112\uffa8\001" +
    "\002\000\004\112\uffab\001\002\000\004\112\206\001\002" +
    "\000\004\112\uffa1\001\002\000\004\112\uffaa\001\002\000" +
    "\004\112\uffa7\001\002\000\004\112\uffa4\001\002\000\004" +
    "\112\uffcd\001\002\000\004\112\uffce\001\002\000\004\112" +
    "\uffa2\001\002\000\004\112\uffcf\001\002\000\004\112\uffad" +
    "\001\002\000\004\112\uffa0\001\002\000\004\112\uffcc\001" +
    "\002\000\004\112\uffa5\001\002\000\010\057\uffd1\107\uffd1" +
    "\122\uffd1\001\002\000\004\106\246\001\002\000\006\105" +
    "\uffc9\110\uffc9\001\002\000\006\105\uffca\110\uffca\001\002" +
    "\000\006\105\uffc4\110\uffc4\001\002\000\006\105\uffc2\110" +
    "\uffc2\001\002\000\006\105\243\110\244\001\002\000\006" +
    "\105\uffc7\110\uffc7\001\002\000\004\106\237\001\002\000" +
    "\006\105\uffc8\110\uffc8\001\002\000\004\106\235\001\002" +
    "\000\004\106\231\001\002\000\004\106\225\001\002\000" +
    "\006\105\uffc5\110\uffc5\001\002\000\006\105\uffc3\110\uffc3" +
    "\001\002\000\004\122\226\001\002\000\004\111\227\001" +
    "\002\000\004\107\230\001\002\000\006\105\uffc6\110\uffc6" +
    "\001\002\000\004\122\232\001\002\000\004\111\233\001" +
    "\002\000\004\107\234\001\002\000\006\105\uffc0\110\uffc0" +
    "\001\002\000\004\107\236\001\002\000\006\105\uffbf\110" +
    "\uffbf\001\002\000\004\122\240\001\002\000\004\111\241" +
    "\001\002\000\004\107\242\001\002\000\006\105\uffc1\110" +
    "\uffc1\001\002\000\010\057\uffd0\107\uffd0\122\uffd0\001\002" +
    "\000\016\007\014\011\222\012\216\013\221\014\220\015" +
    "\207\001\002\000\006\105\uffcb\110\uffcb\001\002\000\004" +
    "\107\247\001\002\000\006\105\uffbe\110\uffbe\001\002\000" +
    "\046\037\176\040\204\044\200\045\172\046\203\047\202" +
    "\050\165\051\170\052\173\053\164\054\167\055\174\056" +
    "\166\104\163\120\201\123\205\124\175\125\161\001\002" +
    "\000\010\057\uffd3\107\uffd3\122\uffd3\001\002\000\010\057" +
    "\uffd5\107\uffd5\122\uffd5\001\002\000\040\002\uffd6\004\uffd6" +
    "\005\uffd6\006\uffd6\007\uffd6\031\uffd6\033\uffd6\034\uffd6\035" +
    "\uffd6\041\uffd6\042\uffd6\043\uffd6\105\uffd6\110\uffd6\122\uffd6" +
    "\001\002\000\014\100\051\102\044\120\043\121\040\122" +
    "\052\001\002\000\004\103\256\001\002\000\004\104\257" +
    "\001\002\000\014\007\014\031\013\033\011\034\017\035" +
    "\031\001\002\000\016\007\014\031\013\033\011\034\017" +
    "\035\031\105\261\001\002\000\040\002\uffb5\004\uffb5\005" +
    "\uffb5\006\uffb5\007\uffb5\031\uffb5\032\262\033\uffb5\034\uffb5" +
    "\035\uffb5\041\uffb5\042\uffb5\043\uffb5\105\uffb5\122\uffb5\001" +
    "\002\000\006\031\013\104\264\001\002\000\036\002\uffb8" +
    "\004\uffb8\005\uffb8\006\uffb8\007\uffb8\031\uffb8\033\uffb8\034" +
    "\uffb8\035\uffb8\041\uffb8\042\uffb8\043\uffb8\105\uffb8\122\uffb8" +
    "\001\002\000\014\007\014\031\013\033\011\034\017\035" +
    "\031\001\002\000\036\002\uffb7\004\uffb7\005\uffb7\006\uffb7" +
    "\007\uffb7\031\uffb7\033\uffb7\034\uffb7\035\uffb7\041\uffb7\042" +
    "\uffb7\043\uffb7\105\uffb7\122\uffb7\001\002\000\016\007\014" +
    "\031\013\033\011\034\017\035\031\105\267\001\002\000" +
    "\036\002\uffb6\004\uffb6\005\uffb6\006\uffb6\007\uffb6\031\uffb6" +
    "\033\uffb6\034\uffb6\035\uffb6\041\uffb6\042\uffb6\043\uffb6\105" +
    "\uffb6\122\uffb6\001\002\000\014\100\051\102\044\120\043" +
    "\121\040\122\052\001\002\000\004\103\272\001\002\000" +
    "\004\104\273\001\002\000\014\007\014\031\013\033\011" +
    "\034\017\035\031\001\002\000\016\007\014\031\013\033" +
    "\011\034\017\035\031\105\275\001\002\000\036\002\uffb1" +
    "\004\uffb1\005\uffb1\006\uffb1\007\uffb1\031\uffb1\033\uffb1\034" +
    "\uffb1\035\uffb1\041\uffb1\042\uffb1\043\uffb1\105\uffb1\122\uffb1" +
    "\001\002\000\006\075\277\112\ufff2\001\002\000\014\100" +
    "\051\102\044\120\043\121\040\122\052\001\002\000\004" +
    "\112\ufff1\001\002\000\034\002\uffff\004\uffff\005\uffff\006" +
    "\uffff\007\uffff\031\uffff\033\uffff\034\uffff\035\uffff\041\uffff" +
    "\042\uffff\043\uffff\122\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\277\000\032\002\015\003\005\004\024\005\020\006" +
    "\014\007\007\016\027\035\011\037\031\040\004\041\017" +
    "\042\025\001\001\000\002\001\001\000\002\001\001\000" +
    "\026\004\300\005\020\006\014\007\007\016\027\035\011" +
    "\037\031\040\004\041\017\042\025\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\006\035\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\010\044\011\040\012\046\013" +
    "\045\014\041\015\047\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\010" +
    "\124\011\040\012\046\013\045\014\041\015\047\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\011\052\012\046\013\045\014\041" +
    "\015\047\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\011\056\012\046\013\045\014\041\015\047\001\001" +
    "\000\014\011\055\012\046\013\045\014\041\015\047\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\015\061\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\014\110\015\047\001\001\000\010\013\107" +
    "\014\041\015\047\001\001\000\006\014\100\015\047\001" +
    "\001\000\010\013\077\014\041\015\047\001\001\000\010" +
    "\013\076\014\041\015\047\001\001\000\010\013\075\014" +
    "\041\015\047\001\001\000\010\013\074\014\041\015\047" +
    "\001\001\000\010\013\073\014\041\015\047\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\015" +
    "\106\001\001\000\004\015\105\001\001\000\004\015\104" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\112" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\016" +
    "\117\033\121\034\116\035\120\037\115\040\004\041\017" +
    "\042\025\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\016\117\034\122" +
    "\035\120\037\115\040\004\041\017\042\025\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\010\130\011\040\012" +
    "\046\013\045\014\041\015\047\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\016\117\033\136\034\116\035\120" +
    "\037\115\040\004\041\017\042\025\001\001\000\020\016" +
    "\117\034\122\035\120\037\115\040\004\041\017\042\025" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\016" +
    "\117\033\142\034\116\035\120\037\115\040\004\041\017" +
    "\042\025\001\001\000\020\016\117\034\122\035\120\037" +
    "\115\040\004\041\017\042\025\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\010\146\011\040\012\046\013" +
    "\045\014\041\015\047\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\017" +
    "\154\020\153\001\001\000\002\001\001\000\004\020\251" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\021" +
    "\161\022\170\043\176\001\001\000\002\001\001\000\002" +
    "\001\001\000\024\016\214\023\213\024\210\025\207\026" +
    "\216\027\222\030\211\031\223\032\212\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\016\214\024" +
    "\244\025\207\026\216\027\222\030\211\031\223\032\212" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\021\250\022\170\043\176\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\010" +
    "\254\011\040\012\046\013\045\014\041\015\047\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\016\117\033" +
    "\257\034\116\035\120\037\115\040\004\041\017\042\025" +
    "\001\001\000\020\016\117\034\122\035\120\037\115\040" +
    "\004\041\017\042\025\001\001\000\004\036\262\001\001" +
    "\000\004\035\264\001\001\000\002\001\001\000\022\016" +
    "\117\033\265\034\116\035\120\037\115\040\004\041\017" +
    "\042\025\001\001\000\002\001\001\000\020\016\117\034" +
    "\122\035\120\037\115\040\004\041\017\042\025\001\001" +
    "\000\002\001\001\000\016\010\270\011\040\012\046\013" +
    "\045\014\041\015\047\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\016\117\033\273\034\116\035\120\037" +
    "\115\040\004\041\017\042\025\001\001\000\020\016\117" +
    "\034\122\035\120\037\115\040\004\041\017\042\025\001" +
    "\001\000\002\001\001\000\002\001\001\000\016\010\277" +
    "\011\040\012\046\013\045\014\041\015\047\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private List<ErroresDeAnalizadores> erroresSintacticos = new ArrayList<>();

    public List<ErroresDeAnalizadores> getSyntaxErrors(){
        return this.erroresSintacticos;
    }

    @Override
    public void syntax_error(Symbol cur_token) {
        String lexema = (cur_token.value != null) ? cur_token.value.toString() : "EOF";
        erroresSintacticos.add(new ErroresDeAnalizadores(lexema, "Sintáctico", cur_token.left, cur_token.right));
    }

    @Override
    public void unrecovered_syntax_error(Symbol cur_token) {
        syntax_error(cur_token);
    }

    public void report_error(String message, Object info){
        Symbol s = (Symbol) info;
        String lexema = (s.value != null) ? s.value.toString() : "EOF";
        erroresSintacticos.add(new ErroresDeAnalizadores(lexema + " -> " + message, "Sintáctico", s.left, s.right));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista_global 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_global ::= lista_global global 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_global",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_global ::= global 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_global",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // global ::= declaracion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("global",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // global ::= asignacion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("global",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // global ::= seccion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("global",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // global ::= condicion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("global",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // global ::= ciclo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("global",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // tipo ::= NUMBER_TYPE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // tipo ::= STRING_TYPE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // tipo ::= SPECIAL_TYPE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // tipo ::= MONO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // tipo ::= SANS_SERIF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // tipo ::= CURSIVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // declaracion ::= tipo IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // declaracion ::= tipo IDENTIFICADOR ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // asignacion ::= IDENTIFICADOR ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("asignacion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expresion ::= expr_logica 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr_logica ::= expr_logica OR expr_logica 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_logica",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr_logica ::= expr_logica AND expr_logica 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_logica",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr_logica ::= NOT expr_logica 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_logica",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr_logica ::= expr_rel 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_logica",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr_rel ::= expr_arit MAYOR expr_arit 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_rel",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr_rel ::= expr_arit MENOR expr_arit 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_rel",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr_rel ::= expr_arit MAYOR_IGUAL expr_arit 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_rel",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr_rel ::= expr_arit MENOR_IGUAL expr_arit 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_rel",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr_rel ::= expr_arit IGUAL expr_arit 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_rel",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr_rel ::= expr_arit DIFERENTE expr_arit 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_rel",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr_rel ::= expr_arit 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_rel",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr_arit ::= expr_arit SUMA termino 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_arit",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr_arit ::= expr_arit RESTA termino 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_arit",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr_arit ::= termino 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_arit",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // termino ::= termino MULTIPLICACION factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // termino ::= termino DIVISION factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // termino ::= termino MODULO factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // termino ::= factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("termino",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // factor ::= factor POTENCIA factor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // factor ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // factor ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // factor ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // factor ::= PARENTESIS_ABRE expresion PARENTESIS_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // factor ::= factor PUNTO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // seccion ::= SECTION CORCHETE_ABRE lista_atributos CORCHETE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccion",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // lista_atributos ::= lista_atributos atributo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_atributos",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // lista_atributos ::= atributo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_atributos",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // atributo ::= IDENTIFICADOR DOS_PUNTOS contenido_atributo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // atributo ::= DRAW DOS_PUNTOS contenido_atributo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // contenido_atributo ::= valor PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("contenido_atributo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // contenido_atributo ::= LLAVE_ABRE lista_elementos LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("contenido_atributo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // valor ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // valor ::= color 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // valor ::= VERTICAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // valor ::= HORIZONTAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // lista_elementos ::= lista_elementos COMA elemento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_elementos",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // lista_elementos ::= elemento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_elementos",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // elemento ::= text_element 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("elemento",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // elemento ::= pregunta 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("elemento",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // elemento ::= seccion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("elemento",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // text_element ::= TEXT CORCHETE_ABRE IDENTIFICADOR DOS_PUNTOS CORCHETE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("text_element",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // pregunta ::= open_q 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("pregunta",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // pregunta ::= drop_q 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("pregunta",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // pregunta ::= select_q 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("pregunta",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // pregunta ::= multiple_q 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("pregunta",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // open_q ::= OPEN_QUESTION CORCHETE_ABRE IDENTIFICADOR DOS_PUNTOS CORCHETE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("open_q",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // drop_q ::= DROP_QUESTION CORCHETE_ABRE IDENTIFICADOR DOS_PUNTOS CORCHETE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("drop_q",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // select_q ::= SELECT_QUESTION CORCHETE_ABRE CORCHETE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("select_q",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // multiple_q ::= MULTIPLE_QUESTION CORCHETE_ABRE CORCHETE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("multiple_q",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // lista_sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // sentencia ::= ciclo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // sentencia ::= condicion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // sentencia ::= seccion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // condicion ::= IF PARENTESIS_ABRE expresion PARENTESIS_CIERRA LLAVE_ABRE lista_sentencias LLAVE_CIERRA else_part 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // else_part ::= ELSE condicion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_part",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // else_part ::= ELSE LLAVE_ABRE lista_sentencias LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_part",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // else_part ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else_part",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // ciclo ::= while_loop 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ciclo",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // ciclo ::= do_while 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ciclo",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // ciclo ::= for_loop 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ciclo",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // while_loop ::= WHILE PARENTESIS_ABRE expresion PARENTESIS_CIERRA LLAVE_ABRE lista_sentencias LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_loop",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // do_while ::= DO LLAVE_ABRE lista_sentencias LLAVE_CIERRA WHILE PARENTESIS_ABRE expresion PARENTESIS_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("do_while",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // for_loop ::= FOR PARENTESIS_ABRE asignacion PUNTO_COMA expresion PUNTO_COMA asignacion PARENTESIS_CIERRA LLAVE_ABRE lista_sentencias LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_loop",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // for_loop ::= FOR PARENTESIS_ABRE IDENTIFICADOR IN ENTERO RANGO ENTERO PARENTESIS_CIERRA LLAVE_ABRE lista_sentencias LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_loop",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // color ::= COLOR_RED 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // color ::= COLOR_BLUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // color ::= COLOR_GREEN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // color ::= COLOR_PURPLE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // color ::= COLOR_SKY 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // color ::= COLOR_YELLOW 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // color ::= COLOR_BLACK 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // color ::= COLOR_WHITE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // color ::= COLOR_HEX 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // color ::= COLOR_RGB 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // color ::= COLOR_HSL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // color ::= LINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // color ::= DOTTED 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // color ::= DOUBLE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
