
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.formularioapp.backen.java.parser;

import java.util.*;
import java_cup.runtime.*;
import com.example.formularioapp.backen.java.ast.*;
import com.example.formularioapp.backen.java.ErroresDeAnalizadores;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\065\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\006\000\002\004\006" +
    "\000\002\004\003\000\002\004\006\000\002\006\005\000" +
    "\002\006\003\000\002\007\005\000\002\007\005\000\002" +
    "\007\005\000\002\007\005\000\002\007\005\000\002\007" +
    "\007\000\002\007\007\000\002\007\005\000\002\007\005" +
    "\000\002\007\005\000\002\007\013\000\002\007\013\000" +
    "\002\007\013\000\002\007\005\000\002\007\005\000\002" +
    "\007\005\000\002\007\005\000\002\007\007\000\002\007" +
    "\005\000\002\005\005\000\002\005\003\000\002\011\005" +
    "\000\002\011\003\000\002\012\005\000\002\013\005\000" +
    "\002\013\003\000\002\010\006\000\002\010\006\000\002" +
    "\010\006\000\002\010\006\000\002\014\003\000\002\014" +
    "\003\000\002\014\003\000\002\014\003\000\002\014\003" +
    "\000\002\014\003\000\002\014\003\000\002\014\003\000" +
    "\002\014\003\000\002\014\003\000\002\014\003\000\002" +
    "\015\003\000\002\015\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\173\000\020\004\007\005\014\006\016\007\010\010" +
    "\015\011\013\012\005\001\002\000\004\002\175\001\002" +
    "\000\004\031\172\001\002\000\022\002\ufffe\004\ufffe\005" +
    "\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\012\ufffe\001\002" +
    "\000\004\031\167\001\002\000\004\031\164\001\002\000" +
    "\030\002\ufffb\004\ufffb\005\ufffb\006\ufffb\007\ufffb\010\ufffb" +
    "\011\ufffb\012\ufffb\032\ufffb\034\ufffb\035\ufffb\001\002\000" +
    "\022\002\000\004\007\005\014\006\016\007\010\010\015" +
    "\011\013\012\005\001\002\000\004\031\160\001\002\000" +
    "\004\031\155\001\002\000\004\031\152\001\002\000\004" +
    "\031\017\001\002\000\032\013\032\014\027\015\030\016" +
    "\026\017\031\020\024\021\025\022\035\023\023\024\034" +
    "\037\021\040\033\001\002\000\006\032\ufff8\035\ufff8\001" +
    "\002\000\004\036\114\001\002\000\006\032\112\035\111" +
    "\001\002\000\004\036\105\001\002\000\004\036\063\001" +
    "\002\000\004\036\061\001\002\000\004\036\057\001\002" +
    "\000\004\036\055\001\002\000\004\036\053\001\002\000" +
    "\004\036\050\001\002\000\004\036\044\001\002\000\004" +
    "\036\042\001\002\000\004\036\040\001\002\000\004\036" +
    "\036\001\002\000\004\037\037\001\002\000\006\032\ufff4" +
    "\035\ufff4\001\002\000\004\037\041\001\002\000\006\032" +
    "\uffe5\035\uffe5\001\002\000\004\040\043\001\002\000\006" +
    "\032\ufff3\035\ufff3\001\002\000\006\041\047\042\046\001" +
    "\002\000\006\032\ufff7\035\ufff7\001\002\000\006\032\uffcd" +
    "\035\uffcd\001\002\000\006\032\uffce\035\uffce\001\002\000" +
    "\006\025\052\026\051\001\002\000\006\032\uffe9\035\uffe9" +
    "\001\002\000\006\032\uffea\035\uffea\001\002\000\006\041" +
    "\047\042\046\001\002\000\006\032\uffe8\035\uffe8\001\002" +
    "\000\006\041\047\042\046\001\002\000\006\032\ufff6\035" +
    "\ufff6\001\002\000\006\041\047\042\046\001\002\000\006" +
    "\032\uffe7\035\uffe7\001\002\000\004\037\062\001\002\000" +
    "\006\032\ufff5\035\ufff5\001\002\000\004\033\064\001\002" +
    "\000\022\004\007\005\014\006\016\007\010\010\015\011" +
    "\013\012\005\031\071\001\002\000\006\034\uffe3\035\uffe3" +
    "\001\002\000\006\034\103\035\102\001\002\000\006\034" +
    "\uffe1\035\uffe1\001\002\000\006\034\077\035\100\001\002" +
    "\000\020\004\007\005\014\006\016\007\010\010\015\011" +
    "\013\012\005\001\002\000\006\032\uffde\035\uffde\001\002" +
    "\000\006\032\075\035\074\001\002\000\020\004\007\005" +
    "\014\006\016\007\010\010\015\011\013\012\005\001\002" +
    "\000\006\034\uffe0\035\uffe0\001\002\000\006\032\uffdf\035" +
    "\uffdf\001\002\000\006\032\ufff1\035\ufff1\001\002\000\004" +
    "\031\071\001\002\000\006\034\uffe2\035\uffe2\001\002\000" +
    "\020\004\007\005\014\006\016\007\010\010\015\011\013" +
    "\012\005\001\002\000\006\032\ufff2\035\ufff2\001\002\000" +
    "\006\034\uffe4\035\uffe4\001\002\000\004\031\106\001\002" +
    "\000\004\037\107\001\002\000\004\032\110\001\002\000" +
    "\006\032\uffe6\035\uffe6\001\002\000\032\013\032\014\027" +
    "\015\030\016\026\017\031\020\024\021\025\022\035\023" +
    "\023\024\034\037\021\040\033\001\002\000\030\002\ufffc" +
    "\004\ufffc\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011\ufffc\012" +
    "\ufffc\032\ufffc\034\ufffc\035\ufffc\001\002\000\006\032\ufff9" +
    "\035\ufff9\001\002\000\012\027\120\043\115\044\117\045" +
    "\116\001\002\000\006\032\ufff0\035\ufff0\001\002\000\006" +
    "\032\uffee\035\uffee\001\002\000\006\032\uffef\035\uffef\001" +
    "\002\000\006\041\047\042\046\001\002\000\004\035\122" +
    "\001\002\000\010\046\124\047\125\050\123\001\002\000" +
    "\004\035\147\001\002\000\004\035\144\001\002\000\004" +
    "\035\126\001\002\000\030\051\130\052\134\053\133\054" +
    "\136\055\135\056\137\057\131\060\141\061\127\062\140" +
    "\063\142\001\002\000\004\030\uffd1\001\002\000\004\030" +
    "\uffd9\001\002\000\004\030\uffd3\001\002\000\004\030\143" +
    "\001\002\000\004\030\uffd7\001\002\000\004\030\uffd8\001" +
    "\002\000\004\030\uffd5\001\002\000\004\030\uffd6\001\002" +
    "\000\004\030\uffd4\001\002\000\004\030\uffd0\001\002\000" +
    "\004\030\uffd2\001\002\000\004\030\uffcf\001\002\000\006" +
    "\032\uffec\035\uffec\001\002\000\030\051\130\052\134\053" +
    "\133\054\136\055\135\056\137\057\131\060\141\061\127" +
    "\062\140\063\142\001\002\000\004\030\146\001\002\000" +
    "\006\032\uffed\035\uffed\001\002\000\030\051\130\052\134" +
    "\053\133\054\136\055\135\056\137\057\131\060\141\061" +
    "\127\062\140\063\142\001\002\000\004\030\151\001\002" +
    "\000\006\032\uffeb\035\uffeb\001\002\000\032\013\032\014" +
    "\027\015\030\016\026\017\031\020\024\021\025\022\035" +
    "\023\023\024\034\037\021\040\033\001\002\000\006\032" +
    "\154\035\111\001\002\000\030\002\uffdc\004\uffdc\005\uffdc" +
    "\006\uffdc\007\uffdc\010\uffdc\011\uffdc\012\uffdc\032\uffdc\034" +
    "\uffdc\035\uffdc\001\002\000\032\013\032\014\027\015\030" +
    "\016\026\017\031\020\024\021\025\022\035\023\023\024" +
    "\034\037\021\040\033\001\002\000\006\032\157\035\111" +
    "\001\002\000\030\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007" +
    "\ufffa\010\ufffa\011\ufffa\012\ufffa\032\ufffa\034\ufffa\035\ufffa" +
    "\001\002\000\032\013\032\014\027\015\030\016\026\017" +
    "\031\020\024\021\025\022\035\023\023\024\034\037\021" +
    "\040\033\001\002\000\006\032\162\035\111\001\002\000" +
    "\030\002\uffdb\004\uffdb\005\uffdb\006\uffdb\007\uffdb\010\uffdb" +
    "\011\uffdb\012\uffdb\032\uffdb\034\uffdb\035\uffdb\001\002\000" +
    "\022\002\uffff\004\uffff\005\uffff\006\uffff\007\uffff\010\uffff" +
    "\011\uffff\012\uffff\001\002\000\032\013\032\014\027\015" +
    "\030\016\026\017\031\020\024\021\025\022\035\023\023" +
    "\024\034\037\021\040\033\001\002\000\006\032\166\035" +
    "\111\001\002\000\030\002\uffdd\004\uffdd\005\uffdd\006\uffdd" +
    "\007\uffdd\010\uffdd\011\uffdd\012\uffdd\032\uffdd\034\uffdd\035" +
    "\uffdd\001\002\000\032\013\032\014\027\015\030\016\026" +
    "\017\031\020\024\021\025\022\035\023\023\024\034\037" +
    "\021\040\033\001\002\000\006\032\171\035\111\001\002" +
    "\000\030\002\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd\010" +
    "\ufffd\011\ufffd\012\ufffd\032\ufffd\034\ufffd\035\ufffd\001\002" +
    "\000\032\013\032\014\027\015\030\016\026\017\031\020" +
    "\024\021\025\022\035\023\023\024\034\037\021\040\033" +
    "\001\002\000\006\032\174\035\111\001\002\000\030\002" +
    "\uffda\004\uffda\005\uffda\006\uffda\007\uffda\010\uffda\011\uffda" +
    "\012\uffda\032\uffda\034\uffda\035\uffda\001\002\000\004\002" +
    "\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\173\000\012\002\003\003\011\004\005\010\010\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\004\162\010\010\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\006" +
    "\021\007\017\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\015\044\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\015\053\001\001\000\002\001\001\000\004\015\055\001" +
    "\001\000\002\001\001\000\004\015\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\004\064\005\065\010\010\011\067\012\066" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\004\071\010\010\013\072" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\004" +
    "\075\010\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\012\100\001\001\000\002\001" +
    "\001\000\006\004\103\010\010\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\112\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\015\120\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\014\131\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\014\144\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\014\147\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\006\152\007\017\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\006\155" +
    "\007\017\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\006\160\007\017\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\006\164\007\017\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\006\167" +
    "\007\017\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\006\172\007\017\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private List<ErroresDeAnalizadores> errores = new ArrayList<>();

    public List<ErroresDeAnalizadores> getErrores(){
        return errores;
    }
    @Override
    public void syntax_error(Symbol s){
        String lex;

        if (s.value != null) {
            lex = s.value.toString();
        } else {
            try {
                lex = symbl_name_from_id(s.sym);
            } catch (Exception e) {
                lex = "TOKEN_" + s.sym;
            }
        }

        errores.add(new ErroresDeAnalizadores(
            lex,
            "Sintáctico",
            "Creación de formulario",
            "Error sintáctico",
            s.left,
            s.right
        ));
    }

    @Override
    public void unrecovered_syntax_error(Symbol s){
        String lex;

        if (s.value != null) {
            lex = s.value.toString();
        } else {
            try {
                lex = symbl_name_from_id(s.sym);
            } catch (Exception e) {
                lex = "TOKEN_" + s.sym;
            }
        }

        errores.add(new ErroresDeAnalizadores(
            lex,
            "Sintáctico",
            "Creación de formulario",
            "Error sintáctico irrecuperable: estructura inválida en la entrada",
            s.left,
            s.right
        ));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Nodo start_val = (Nodo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= lista 
            {
              Nodo RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<Nodo> l = (List<Nodo>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NodoPrograma(l,0,0); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista ::= lista componente 
            {
              List<Nodo> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<Nodo> l = (List<Nodo>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoComponente c = (NodoComponente)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 l.add(c); RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista ::= componente 
            {
              List<Nodo> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoComponente c = (NodoComponente)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 List<Nodo> l = new ArrayList<>(); l.add(c); RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // componente ::= SECTION CORCHETE_ABRE lista_atributos CORCHETE_CIERRA 
            {
              NodoComponente RESULT =null;
		int atrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int atrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Map<String,Object> atr = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
         List<NodoComponente> hijos = (List<NodoComponente>) atr.getOrDefault("elements", new ArrayList<>());
         RESULT = new NodoSeccion(atr, hijos,0,0);
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("componente",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // componente ::= TEXT CORCHETE_ABRE lista_atributos CORCHETE_CIERRA 
            {
              NodoComponente RESULT =null;
		int atrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int atrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Map<String,Object> atr = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
         String contenido = (String) atr.get("content");
         NodoTexto nodo = new NodoTexto(contenido,0,0);
         RESULT = nodo;
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("componente",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // componente ::= pregunta 
            {
              NodoComponente RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoComponente p = (NodoComponente)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = p; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("componente",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // componente ::= TABLE CORCHETE_ABRE lista_atributos CORCHETE_CIERRA 
            {
              NodoComponente RESULT =null;
		int atrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int atrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Map<String,Object> atr = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
         List<List<NodoComponente>> f = (List<List<NodoComponente>>) atr.get("elements");
         RESULT = new NodoTabla(f,0,0);
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("componente",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // lista_atributos ::= lista_atributos COMA atributo 
            {
              Map<String,Object> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Map<String,Object> l = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Map<String,Object> a = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 l.putAll(a); RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_atributos",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_atributos ::= atributo 
            {
              Map<String,Object> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Map<String,Object> a = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = a; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_atributos",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // atributo ::= WIDTH DOS_PUNTOS valor 
            {
              Map<String,Object> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number v = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Map<String,Object> m = new HashMap<>(); m.put("width", v); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // atributo ::= HEIGHT DOS_PUNTOS valor 
            {
              Map<String,Object> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number v = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Map<String,Object> m = new HashMap<>(); m.put("height", v); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // atributo ::= LABEL DOS_PUNTOS TEXTO 
            {
              Map<String,Object> RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Map<String,Object> m = new HashMap<>(); m.put("label", t); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // atributo ::= CONTENT DOS_PUNTOS TEXTO 
            {
              Map<String,Object> RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Map<String,Object> m = new HashMap<>(); m.put("content", t); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // atributo ::= IDENTIFICADOR DOS_PUNTOS IDENTIFICADOR 
            {
              Map<String,Object> RESULT =null;
		int id1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Map<String,Object> m = new HashMap<>(); m.put("id", id2); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // atributo ::= ELEMENTS DOS_PUNTOS LLAVE_ABRE lista_componentes LLAVE_CIERRA 
            {
              Map<String,Object> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<NodoComponente> l = (List<NodoComponente>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 Map<String,Object> m = new HashMap<>(); m.put("elements", l); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // atributo ::= ELEMENTS DOS_PUNTOS LLAVE_ABRE filas LLAVE_CIERRA 
            {
              Map<String,Object> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<List<NodoComponente>> f = (List<List<NodoComponente>>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 Map<String,Object> m = new HashMap<>(); m.put("elements", f); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // atributo ::= TEXTO DOS_PUNTOS MONO 
            {
              Map<String,Object> RESULT =null;
		 Map<String,Object> m = new HashMap<>(); m.put("font","MONO"); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // atributo ::= TEXTO DOS_PUNTOS SANS_SERIF 
            {
              Map<String,Object> RESULT =null;
		 Map<String,Object> m = new HashMap<>(); m.put("font","SANS_SERIF"); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // atributo ::= TEXTO DOS_PUNTOS CURSIVE 
            {
              Map<String,Object> RESULT =null;
		 Map<String,Object> m = new HashMap<>(); m.put("font","CURSIVE"); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // atributo ::= TEXTO DOS_PUNTOS PARENTESIS_ABRE valor COMA LINE COMA color PARENTESIS_CIERRA 
            {
              Map<String,Object> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Number v = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoColor c = (NodoColor)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 Map<String,Object> m = new HashMap<>(); m.put("border","LINE"); m.put("thickness", v); m.put("color", c); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // atributo ::= TEXTO DOS_PUNTOS PARENTESIS_ABRE valor COMA DOTTED COMA color PARENTESIS_CIERRA 
            {
              Map<String,Object> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Number v = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoColor c = (NodoColor)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 Map<String,Object> m = new HashMap<>(); m.put("border","DOTTED"); m.put("thickness", v); m.put("color", c); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // atributo ::= TEXTO DOS_PUNTOS PARENTESIS_ABRE valor COMA DOUBLE COMA color PARENTESIS_CIERRA 
            {
              Map<String,Object> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Number v = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		NodoColor c = (NodoColor)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 Map<String,Object> m = new HashMap<>(); m.put("border","DOUBLE"); m.put("thickness", v); m.put("color", c); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // atributo ::= ORIENTATION DOS_PUNTOS VERTICAL 
            {
              Map<String,Object> RESULT =null;
		 Map<String,Object> m = new HashMap<>(); m.put("orientation","VERTICAL"); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // atributo ::= ORIENTATION DOS_PUNTOS HORIZONTAL 
            {
              Map<String,Object> RESULT =null;
		 Map<String,Object> m = new HashMap<>(); m.put("orientation","HORIZONTAL"); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // atributo ::= POINTX DOS_PUNTOS valor 
            {
              Map<String,Object> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number v = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Map<String,Object> m = new HashMap<>(); m.put("pointX", v); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // atributo ::= POINTY DOS_PUNTOS valor 
            {
              Map<String,Object> RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Number v = (Number)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Map<String,Object> m = new HashMap<>(); m.put("pointY", v); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // atributo ::= OPTIONS DOS_PUNTOS CORCHETE_ABRE TEXTO CORCHETE_CIERRA 
            {
              Map<String,Object> RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
         List<String> list = new ArrayList<>();
         list.add(t);
         Map<String,Object> m = new HashMap<>();
         m.put("options", list);
         RESULT = m;
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // atributo ::= CORRECT DOS_PUNTOS TEXTO 
            {
              Map<String,Object> RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 Map<String,Object> m = new HashMap<>(); m.put("correct", t.equals("true")); RESULT = m; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atributo",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // lista_componentes ::= lista_componentes COMA componente 
            {
              List<NodoComponente> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<NodoComponente> l = (List<NodoComponente>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoComponente c = (NodoComponente)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 l.add(c); RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_componentes",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // lista_componentes ::= componente 
            {
              List<NodoComponente> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoComponente c = (NodoComponente)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 List<NodoComponente> l = new ArrayList<>(); l.add(c); RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_componentes",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // filas ::= filas COMA fila 
            {
              List<List<NodoComponente>> RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<List<NodoComponente>> f = (List<List<NodoComponente>>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<NodoComponente> r = (List<NodoComponente>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 f.add(r); RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("filas",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // filas ::= fila 
            {
              List<List<NodoComponente>> RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		List<NodoComponente> r = (List<NodoComponente>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 List<List<NodoComponente>> f = new ArrayList<>(); f.add(r); RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("filas",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // fila ::= CORCHETE_ABRE celdas CORCHETE_CIERRA 
            {
              List<NodoComponente> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<NodoComponente> c = (List<NodoComponente>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = c; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("fila",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // celdas ::= celdas COMA componente 
            {
              List<NodoComponente> RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<NodoComponente> c = (List<NodoComponente>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoComponente n = (NodoComponente)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 c.add(n); RESULT = c; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("celdas",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // celdas ::= componente 
            {
              List<NodoComponente> RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		NodoComponente n = (NodoComponente)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 List<NodoComponente> c = new ArrayList<>(); c.add(n); RESULT = c; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("celdas",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // pregunta ::= OPEN_QUESTION CORCHETE_ABRE lista_atributos CORCHETE_CIERRA 
            {
              NodoComponente RESULT =null;
		int atrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int atrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Map<String,Object> atr = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new NodoPreguntaAbierta((String)atr.get("label"),0,0); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pregunta",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // pregunta ::= DROP_QUESTION CORCHETE_ABRE lista_atributos CORCHETE_CIERRA 
            {
              NodoComponente RESULT =null;
		int atrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int atrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Map<String,Object> atr = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new NodoPreguntaSeleccion((String)atr.get("label"), (List<String>)atr.get("options"), (Boolean)atr.get("correct"),0,0); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pregunta",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // pregunta ::= SELECT_QUESTION CORCHETE_ABRE lista_atributos CORCHETE_CIERRA 
            {
              NodoComponente RESULT =null;
		int atrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int atrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Map<String,Object> atr = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new NodoPreguntaSeleccion((String)atr.get("label"), (List<String>)atr.get("options"), (Boolean)atr.get("correct"),0,0); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pregunta",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // pregunta ::= MULTIPLE_QUESTION CORCHETE_ABRE lista_atributos CORCHETE_CIERRA 
            {
              NodoComponente RESULT =null;
		int atrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int atrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Map<String,Object> atr = (Map<String,Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new NodoPreguntaSeleccion((String)atr.get("label"), (List<String>)atr.get("options"), (Boolean)atr.get("correct"),0,0); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("pregunta",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // color ::= COLOR_RED 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // color ::= COLOR_BLUE 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // color ::= COLOR_GREEN 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // color ::= COLOR_PURPLE 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // color ::= COLOR_SKY 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // color ::= COLOR_YELLOW 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // color ::= COLOR_BLACK 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // color ::= COLOR_WHITE 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // color ::= COLOR_HEX 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // color ::= COLOR_RGB 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // color ::= COLOR_HSL 
            {
              NodoColor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("color",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // valor ::= ENTERO 
            {
              Number RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // valor ::= DECIMAL 
            {
              Number RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double d = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = d; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
