
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.formularioapp.backen.java.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STYLE_SIZE = 73;
  public static final int HORIZONTAL = 20;
  public static final int SELECT_QUESTION = 7;
  public static final int IDENTIFICADOR = 30;
  public static final int STYLE_BACKGROUND = 71;
  public static final int PARENTESIS_ABRE = 21;
  public static final int COLOR_WHITE = 44;
  public static final int TABLE = 3;
  public static final int COLOR_BLACK = 43;
  public static final int PARENTESIS_CIERRA = 22;
  public static final int COLOR_HEX = 48;
  public static final int MAYOR = 57;
  public static final int COLOR_PURPLE = 46;
  public static final int TEXTO = 29;
  public static final int SANS_SERIF = 34;
  public static final int DROP_QUESTION = 6;
  public static final int ELEMENTS = 14;
  public static final int NUMBER_T = 67;
  public static final int OPEN_QUESTION = 5;
  public static final int POT = 55;
  public static final int POR = 53;
  public static final int DOUBLE = 38;
  public static final int CORCHETE_ABRE = 23;
  public static final int NOT = 65;
  public static final int TEXT = 4;
  public static final int DOS_PUNTOS = 28;
  public static final int STYLE_FONT = 72;
  public static final int WIDTH = 9;
  public static final int STYLES = 39;
  public static final int MOD = 56;
  public static final int COMA = 27;
  public static final int LLAVE_CIERRA = 26;
  public static final int ENTERO = 31;
  public static final int CURSIVE = 35;
  public static final int MONO = 33;
  public static final int IGUAL = 61;
  public static final int DECIMAL = 32;
  public static final int DIV = 54;
  public static final int ORIENTATION = 13;
  public static final int MENOS = 52;
  public static final int MULTIPLE_QUESTION = 8;
  public static final int MENOR = 58;
  public static final int MAS = 51;
  public static final int COLOR_RGB = 49;
  public static final int LLAVE_ABRE = 25;
  public static final int CORRECT = 18;
  public static final int CONTENT = 16;
  public static final int EOF = 0;
  public static final int DIF = 62;
  public static final int VERTICAL = 19;
  public static final int LINE = 36;
  public static final int STYLE_COLOR = 70;
  public static final int LABEL = 15;
  public static final int MENORIGUAL = 60;
  public static final int STRING_T = 68;
  public static final int OR = 64;
  public static final int error = 1;
  public static final int STYLE_BORDER = 74;
  public static final int IGUAL_ASIG = 69;
  public static final int DOTTED = 37;
  public static final int COLOR_SKY = 45;
  public static final int COLOR_GREEN = 42;
  public static final int HEIGHT = 10;
  public static final int MAYORIGUAL = 59;
  public static final int COLOR_RED = 40;
  public static final int COLOR_HSL = 50;
  public static final int POINTY = 12;
  public static final int OPTIONS = 17;
  public static final int POINTX = 11;
  public static final int AND = 63;
  public static final int COLOR_BLUE = 41;
  public static final int COLOR_YELLOW = 47;
  public static final int WHO_IS_THAT_POKEMON = 66;
  public static final int CORCHETE_CIERRA = 24;
  public static final int SECTION = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SECTION",
  "TABLE",
  "TEXT",
  "OPEN_QUESTION",
  "DROP_QUESTION",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "WIDTH",
  "HEIGHT",
  "POINTX",
  "POINTY",
  "ORIENTATION",
  "ELEMENTS",
  "LABEL",
  "CONTENT",
  "OPTIONS",
  "CORRECT",
  "VERTICAL",
  "HORIZONTAL",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "CORCHETE_ABRE",
  "CORCHETE_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "COMA",
  "DOS_PUNTOS",
  "TEXTO",
  "IDENTIFICADOR",
  "ENTERO",
  "DECIMAL",
  "MONO",
  "SANS_SERIF",
  "CURSIVE",
  "LINE",
  "DOTTED",
  "DOUBLE",
  "STYLES",
  "COLOR_RED",
  "COLOR_BLUE",
  "COLOR_GREEN",
  "COLOR_BLACK",
  "COLOR_WHITE",
  "COLOR_SKY",
  "COLOR_PURPLE",
  "COLOR_YELLOW",
  "COLOR_HEX",
  "COLOR_RGB",
  "COLOR_HSL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POT",
  "MOD",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "IGUAL",
  "DIF",
  "AND",
  "OR",
  "NOT",
  "WHO_IS_THAT_POKEMON",
  "NUMBER_T",
  "STRING_T",
  "IGUAL_ASIG",
  "STYLE_COLOR",
  "STYLE_BACKGROUND",
  "STYLE_FONT",
  "STYLE_SIZE",
  "STYLE_BORDER"
  };
}

