// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer2.jflex

package com.example.formularioapp.backen.java.lexer;

import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;

import com.example.formularioapp.backen.java.parser.sym;
import com.example.formularioapp.backen.java.parser.symPKM;
import com.example.formularioapp.backen.java.ErroresDeAnalizadores; 


@SuppressWarnings("fallthrough")
public class LexerPKM implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int DENTRO_CADENA = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\5"+
    "\1\6\1\7\1\10\4\0\1\11\1\12\2\0\1\13"+
    "\1\14\1\15\1\16\12\17\1\20\1\0\1\21\1\22"+
    "\1\23\1\0\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\36\1\45\1\46\1\47\1\50"+
    "\1\51\1\36\1\52\1\53\1\54\1\55\1\0\1\56"+
    "\1\57\1\60\1\0\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\36\1\45\1\46\1\47\1\50"+
    "\1\51\1\36\1\52\1\53\1\54\1\61\1\0\1\62"+
    "\7\0\1\3\115\0\1\63\6\0\1\64\30\0\1\63"+
    "\6\0\1\64\65\0\2\65\115\0\1\66\u01a8\0\2\3"+
    "\u0100\0\1\67\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\2\1\1\1\4\2\1"+
    "\1\5\1\6\1\7\1\10\16\11\1\12\1\13\1\1"+
    "\1\14\1\15\1\1\3\2\3\0\1\5\1\16\1\0"+
    "\1\5\3\0\1\17\1\0\16\11\1\0\2\11\1\0"+
    "\5\11\1\0\4\11\4\0\1\20\1\2\3\0\1\5"+
    "\6\0\1\11\1\0\7\11\1\0\7\11\1\0\2\11"+
    "\1\0\6\11\1\0\4\11\5\0\1\2\11\0\1\11"+
    "\1\0\2\11\1\0\4\11\1\0\2\11\2\0\1\21"+
    "\2\11\1\0\1\11\1\22\2\11\1\0\2\23\1\24"+
    "\1\11\1\0\1\25\1\11\1\0\2\11\1\26\1\11"+
    "\1\26\1\11\1\27\2\11\5\0\1\2\4\0\1\30"+
    "\4\0\1\11\1\0\2\11\1\0\1\11\1\31\2\11"+
    "\1\0\2\11\2\0\2\11\1\0\1\11\1\32\1\11"+
    "\1\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\33\1\34\2\11\2\0\1\33\4\0\1\2\10\0"+
    "\1\11\1\0\2\11\1\0\1\35\2\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\11\2\36\1\37\1\11\1\0"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\1\11\1\40"+
    "\1\0\1\11\2\0\1\40\3\0\1\41\1\0\1\42"+
    "\4\0\1\43\1\11\1\0\1\44\1\11\1\0\1\45"+
    "\2\46\1\11\1\0\1\11\1\0\1\47\1\11\1\0"+
    "\1\11\2\0\1\11\1\0\2\50\1\11\2\0\1\11"+
    "\3\0\1\51\1\0\1\52\1\0\1\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\1\11\1\0\2\53"+
    "\1\0\1\11\1\0\1\11\2\0\2\54\1\0\1\52"+
    "\1\55\1\11\1\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\1\11\3\0\1\52"+
    "\2\56\1\11\1\0\1\11\1\0\2\57\1\60\2\61"+
    "\1\62\2\0\1\11\1\0\1\11\3\0\1\63\1\11"+
    "\3\0\1\64\14\0\1\65\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[402];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\160\0\250\0\160\0\340\0\u0118"+
    "\0\160\0\u0150\0\u0188\0\u01c0\0\u01f8\0\160\0\160\0\u0230"+
    "\0\u0268\0\u02a0\0\u02d8\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0"+
    "\0\u0428\0\u0460\0\u0498\0\u04d0\0\u0508\0\160\0\160\0\u0540"+
    "\0\u0578\0\160\0\u05b0\0\u05e8\0\u0620\0\u0658\0\u0118\0\u0690"+
    "\0\u06c8\0\u0700\0\160\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818"+
    "\0\160\0\u0850\0\u0888\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0"+
    "\0\u09d8\0\u0a10\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60"+
    "\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20"+
    "\0\u0d58\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0"+
    "\0\u0f18\0\u0f50\0\u05e8\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u0738"+
    "\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u11b8\0\u11f0"+
    "\0\u1228\0\u1260\0\u1298\0\u12d0\0\u1308\0\u1340\0\u1378\0\u13b0"+
    "\0\u13e8\0\u1420\0\u1458\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570"+
    "\0\u15a8\0\u15e0\0\u1618\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u1730"+
    "\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880\0\u18b8\0\u18f0"+
    "\0\u1928\0\u1960\0\u1998\0\u19d0\0\u1a08\0\u1a40\0\u1a78\0\u1ab0"+
    "\0\u1ae8\0\u1b20\0\u1b58\0\u1b90\0\u1bc8\0\u1c00\0\u1c38\0\u1c70"+
    "\0\u1ca8\0\u1ce0\0\u1d18\0\u1d50\0\u1d88\0\u1dc0\0\u1df8\0\u1e30"+
    "\0\u1e68\0\u1ea0\0\u1ed8\0\u0380\0\u1f10\0\u1f48\0\u1f80\0\u1fb8"+
    "\0\u0380\0\u1ff0\0\u2028\0\u2060\0\u0380\0\160\0\u0380\0\u2098"+
    "\0\u20d0\0\u0380\0\u2108\0\u2140\0\u2178\0\u21b0\0\u0380\0\u21e8"+
    "\0\160\0\u2220\0\u0380\0\u2258\0\u2290\0\u22c8\0\u2300\0\u2338"+
    "\0\u2370\0\u23a8\0\u23e0\0\u2418\0\u2450\0\u2488\0\u24c0\0\160"+
    "\0\u24f8\0\u2530\0\u2568\0\u25a0\0\u25d8\0\u2610\0\u2648\0\u2680"+
    "\0\u26b8\0\u26f0\0\u0380\0\u2728\0\u2760\0\u2798\0\u27d0\0\u2808"+
    "\0\u2840\0\u2878\0\u28b0\0\u28e8\0\u2920\0\u2958\0\160\0\u2990"+
    "\0\u29c8\0\u2a00\0\u2a38\0\u2a70\0\u2aa8\0\u2ae0\0\u2b18\0\u2b50"+
    "\0\u2b88\0\u0380\0\u0380\0\u2bc0\0\u2bf8\0\u2c30\0\u2c68\0\160"+
    "\0\u2ca0\0\u2cd8\0\u2d10\0\u2d48\0\u2d80\0\u2db8\0\u2df0\0\u2e28"+
    "\0\u2e60\0\u2e98\0\u2ed0\0\u2f08\0\u2f40\0\u2f78\0\u2fb0\0\u2fe8"+
    "\0\u3020\0\u3058\0\u0380\0\u3090\0\u30c8\0\u3100\0\u3138\0\u3170"+
    "\0\u31a8\0\u31e0\0\u3218\0\u0380\0\160\0\160\0\u3250\0\u3288"+
    "\0\u32c0\0\u32f8\0\u3330\0\u3368\0\u33a0\0\u33d8\0\u3410\0\u3448"+
    "\0\u0380\0\u3480\0\u34b8\0\u34f0\0\u3528\0\160\0\u3560\0\u3598"+
    "\0\u35d0\0\u05e8\0\u3608\0\160\0\u3640\0\u3678\0\u36b0\0\u36e8"+
    "\0\160\0\u3720\0\u3758\0\160\0\u3790\0\u37c8\0\u0380\0\u0380"+
    "\0\160\0\u3800\0\u3838\0\u3870\0\u38a8\0\u0380\0\u38e0\0\u3918"+
    "\0\u3950\0\u3988\0\u39c0\0\u39f8\0\u3a30\0\u0380\0\160\0\u3a68"+
    "\0\u3aa0\0\u3ad8\0\u3b10\0\u3b48\0\u3b80\0\u3bb8\0\160\0\u3bf0"+
    "\0\u3c28\0\u3c60\0\u3c98\0\u3cd0\0\u3d08\0\u3d40\0\u3d78\0\u3db0"+
    "\0\u3de8\0\u3e20\0\u3e58\0\u3e90\0\u3ec8\0\u3f00\0\u3f00\0\u3f38"+
    "\0\u3f70\0\u3fa8\0\u3fe0\0\u4018\0\u0380\0\160\0\u4050\0\u4088"+
    "\0\160\0\u40c0\0\u40f8\0\u4130\0\u4168\0\u41a0\0\u41d8\0\u4210"+
    "\0\u4248\0\u4280\0\u42b8\0\u42f0\0\u4328\0\u4360\0\u4398\0\u43d0"+
    "\0\u4408\0\160\0\u0380\0\160\0\u4440\0\u4478\0\u44b0\0\u44e8"+
    "\0\u0380\0\160\0\160\0\u0380\0\160\0\160\0\u4520\0\u4558"+
    "\0\u4590\0\u45c8\0\u4600\0\u4638\0\u4670\0\u46a8\0\160\0\u46e0"+
    "\0\u4718\0\u4750\0\u4788\0\160\0\u47c0\0\u47f8\0\u4830\0\u4868"+
    "\0\u48a0\0\u48d8\0\u4910\0\u4948\0\u4980\0\u49b8\0\u49f0\0\u4a28"+
    "\0\160\0\160";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[402];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\5\1\4\1\3\1\6\1\7"+
    "\1\10\1\3\1\11\1\12\1\3\1\13\1\14\1\3"+
    "\1\15\1\16\1\17\1\3\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\3\26\1\30\1\31\1\26"+
    "\1\32\2\26\1\33\1\34\1\26\1\35\3\26\3\3"+
    "\1\26\1\36\1\37\3\3\1\40\1\3\7\41\1\42"+
    "\14\41\1\43\43\41\72\0\1\4\65\0\2\44\1\0"+
    "\5\44\1\45\6\44\1\46\5\44\6\46\35\44\5\0"+
    "\1\47\6\0\1\50\2\0\1\51\67\0\1\52\73\0"+
    "\1\53\61\0\1\54\1\0\1\55\55\0\1\56\1\57"+
    "\5\0\1\60\1\0\1\61\1\62\67\0\1\26\5\0"+
    "\1\26\1\63\21\26\1\64\4\26\3\0\1\26\26\0"+
    "\1\26\5\0\1\65\15\26\1\66\11\26\3\0\1\26"+
    "\26\0\1\26\5\0\16\26\1\67\4\26\1\70\4\26"+
    "\3\0\1\26\26\0\1\26\5\0\4\26\1\71\13\26"+
    "\1\72\7\26\3\0\1\26\26\0\1\26\5\0\13\26"+
    "\1\73\14\26\3\0\1\26\26\0\1\26\5\0\1\74"+
    "\3\26\1\75\11\26\1\76\11\26\3\0\1\26\26\0"+
    "\1\26\5\0\30\26\3\0\1\26\26\0\1\26\5\0"+
    "\16\26\1\77\11\26\3\0\1\26\26\0\1\26\5\0"+
    "\10\26\1\100\17\26\3\0\1\26\4\0\1\101\21\0"+
    "\1\26\5\0\16\26\1\102\4\26\1\103\4\26\3\0"+
    "\1\26\3\0\1\104\22\0\1\26\5\0\17\26\1\105"+
    "\10\26\3\0\1\26\26\0\1\26\5\0\1\106\3\26"+
    "\1\107\3\26\1\110\11\26\1\111\5\26\3\0\1\26"+
    "\4\0\1\112\21\0\1\26\5\0\1\113\3\26\1\114"+
    "\11\26\1\115\11\26\3\0\1\26\26\0\1\26\5\0"+
    "\4\26\1\116\23\26\3\0\1\26\34\0\1\117\3\0"+
    "\1\120\3\0\1\112\11\0\1\121\15\0\1\112\2\0"+
    "\7\41\1\0\14\41\1\0\43\41\55\0\1\122\12\0"+
    "\2\44\1\0\67\44\1\0\5\44\1\123\61\44\1\0"+
    "\14\44\1\124\5\44\6\124\35\44\17\0\1\51\55\0"+
    "\1\125\5\0\1\126\1\0\1\127\1\0\1\51\65\0"+
    "\1\54\1\0\1\52\67\0\1\130\65\0\1\54\1\131"+
    "\1\52\1\132\54\0\1\56\6\0\1\60\2\0\1\62"+
    "\64\0\1\133\72\0\1\62\55\0\1\134\5\0\1\135"+
    "\1\0\1\136\1\0\1\62\67\0\1\26\5\0\10\26"+
    "\1\137\17\26\3\0\1\26\4\0\1\140\21\0\1\26"+
    "\5\0\22\26\1\141\5\26\3\0\1\26\26\0\1\26"+
    "\5\0\2\26\1\142\25\26\3\0\1\26\26\0\1\26"+
    "\5\0\20\26\1\143\7\26\3\0\1\26\26\0\1\26"+
    "\5\0\13\26\1\144\1\26\1\145\12\26\3\0\1\26"+
    "\26\0\1\26\5\0\20\26\1\146\7\26\3\0\1\26"+
    "\26\0\1\26\5\0\21\26\1\147\6\26\3\0\1\26"+
    "\5\0\1\150\20\0\1\26\5\0\16\26\1\151\11\26"+
    "\3\0\1\26\26\0\1\26\5\0\4\26\1\152\23\26"+
    "\3\0\1\26\26\0\1\26\5\0\14\26\1\153\13\26"+
    "\3\0\1\26\26\0\1\26\5\0\2\26\1\154\25\26"+
    "\3\0\1\26\26\0\1\26\5\0\15\26\1\155\12\26"+
    "\3\0\1\26\26\0\1\26\5\0\20\26\1\156\7\26"+
    "\3\0\1\26\26\0\1\26\5\0\15\26\1\157\12\26"+
    "\3\0\1\26\51\0\1\160\44\0\1\26\5\0\15\26"+
    "\1\161\12\26\3\0\1\26\26\0\1\26\5\0\13\26"+
    "\1\162\14\26\3\0\1\26\47\0\1\163\46\0\1\26"+
    "\5\0\4\26\1\164\23\26\3\0\1\26\26\0\1\26"+
    "\5\0\15\26\1\165\12\26\3\0\1\26\26\0\1\26"+
    "\5\0\2\26\1\166\10\26\1\167\14\26\3\0\1\26"+
    "\26\0\1\26\5\0\27\26\1\170\3\0\1\26\26\0"+
    "\1\26\5\0\26\26\1\171\1\26\3\0\1\26\63\0"+
    "\1\172\32\0\1\26\5\0\1\26\1\173\26\26\3\0"+
    "\1\26\26\0\1\26\5\0\25\26\1\174\2\26\3\0"+
    "\1\26\26\0\1\26\5\0\22\26\1\175\5\26\3\0"+
    "\1\26\26\0\1\26\5\0\20\26\1\176\7\26\3\0"+
    "\1\26\51\0\1\177\54\0\1\200\10\0\1\201\102\0"+
    "\1\202\34\0\1\203\47\0\2\44\1\0\14\44\1\204"+
    "\5\44\6\204\35\44\5\0\1\125\5\0\1\126\61\0"+
    "\1\126\6\0\1\205\2\0\1\206\67\0\1\207\67\0"+
    "\1\210\67\0\1\211\64\0\1\212\60\0\1\134\5\0"+
    "\1\135\61\0\1\135\6\0\1\213\2\0\1\214\67\0"+
    "\1\215\67\0\1\26\5\0\4\26\1\216\23\26\3\0"+
    "\1\26\40\0\1\217\55\0\1\26\5\0\7\26\1\220"+
    "\20\26\3\0\1\26\26\0\1\26\5\0\12\26\1\221"+
    "\15\26\3\0\1\26\6\0\1\222\17\0\1\26\5\0"+
    "\3\26\1\223\24\26\3\0\1\26\26\0\1\26\5\0"+
    "\16\26\1\224\11\26\3\0\1\26\26\0\1\26\5\0"+
    "\22\26\1\225\5\26\3\0\1\26\26\0\1\26\5\0"+
    "\21\26\1\226\6\26\3\0\1\26\5\0\1\227\20\0"+
    "\1\26\5\0\2\26\1\230\14\26\1\231\10\26\3\0"+
    "\1\26\36\0\1\232\14\0\1\233\42\0\1\26\5\0"+
    "\17\26\1\234\10\26\3\0\1\26\26\0\1\26\5\0"+
    "\14\26\1\235\13\26\3\0\1\26\26\0\1\26\5\0"+
    "\10\26\1\236\17\26\3\0\1\26\4\0\1\237\21\0"+
    "\1\26\5\0\7\26\1\240\20\26\3\0\1\26\26\0"+
    "\1\26\5\0\22\26\1\241\5\26\3\0\1\26\26\0"+
    "\1\26\5\0\1\242\7\26\1\243\17\26\3\0\1\26"+
    "\4\0\1\244\21\0\1\26\5\0\4\26\1\245\23\26"+
    "\3\0\1\26\40\0\1\246\55\0\1\26\5\0\16\26"+
    "\1\247\11\26\3\0\1\26\26\0\1\26\5\0\22\26"+
    "\1\250\5\26\3\0\1\26\56\0\1\251\37\0\1\26"+
    "\5\0\15\26\1\252\12\26\3\0\1\26\26\0\1\26"+
    "\5\0\21\26\1\253\6\26\3\0\1\26\5\0\1\254"+
    "\20\0\1\26\5\0\22\26\1\255\5\26\3\0\1\26"+
    "\26\0\1\26\5\0\4\26\1\256\23\26\3\0\1\26"+
    "\26\0\1\26\5\0\4\26\1\257\23\26\3\0\1\26"+
    "\26\0\1\26\5\0\13\26\1\260\14\26\3\0\1\26"+
    "\40\0\1\261\55\0\1\26\5\0\13\26\1\262\14\26"+
    "\3\0\1\26\26\0\1\26\5\0\22\26\1\263\5\26"+
    "\3\0\1\26\26\0\1\26\5\0\1\264\27\26\3\0"+
    "\1\26\26\0\1\26\5\0\22\26\1\265\5\26\3\0"+
    "\1\26\55\0\1\254\17\0\1\254\50\0\1\266\51\0"+
    "\1\267\76\0\1\270\75\0\1\271\10\0\1\272\6\0"+
    "\1\271\1\0\2\44\1\0\14\44\1\273\5\44\6\273"+
    "\35\44\17\0\1\206\55\0\1\274\5\0\1\275\1\0"+
    "\1\276\1\0\1\206\55\0\1\125\5\0\1\126\3\0"+
    "\1\207\67\0\1\277\67\0\1\300\50\0\14\212\1\301"+
    "\6\212\1\0\44\212\17\0\1\214\55\0\1\302\5\0"+
    "\1\303\1\0\1\304\1\0\1\214\55\0\1\134\5\0"+
    "\1\135\3\0\1\215\67\0\1\26\5\0\20\26\1\305"+
    "\7\26\3\0\1\26\54\0\1\306\41\0\1\26\5\0"+
    "\16\26\1\307\11\26\3\0\1\26\26\0\1\26\5\0"+
    "\6\26\1\310\21\26\3\0\1\26\42\0\1\311\53\0"+
    "\1\26\5\0\4\26\1\312\23\26\3\0\1\26\26\0"+
    "\1\26\5\0\20\26\1\313\7\26\3\0\1\26\26\0"+
    "\1\26\5\0\4\26\1\314\23\26\3\0\1\26\26\0"+
    "\1\26\5\0\10\26\1\315\17\26\3\0\1\26\4\0"+
    "\1\316\37\0\1\316\27\0\1\316\21\0\1\26\5\0"+
    "\20\26\1\317\7\26\3\0\1\26\26\0\1\26\5\0"+
    "\13\26\1\320\14\26\3\0\1\26\54\0\1\321\62\0"+
    "\1\322\46\0\1\26\5\0\4\26\1\323\23\26\3\0"+
    "\1\26\26\0\1\26\5\0\13\26\1\324\14\26\3\0"+
    "\1\26\47\0\1\325\46\0\1\26\5\0\1\326\27\26"+
    "\3\0\1\26\26\0\1\26\1\327\4\0\30\26\3\0"+
    "\1\26\26\0\1\26\5\0\27\26\1\330\3\0\1\26"+
    "\63\0\1\331\32\0\1\26\5\0\10\26\1\332\17\26"+
    "\3\0\1\26\4\0\1\333\37\0\1\334\27\0\1\334"+
    "\21\0\1\26\5\0\30\26\3\0\1\335\67\0\1\336"+
    "\26\0\1\26\5\0\10\26\1\337\17\26\3\0\1\26"+
    "\4\0\1\340\21\0\1\26\5\0\2\26\1\341\25\26"+
    "\3\0\1\26\26\0\1\26\5\0\4\26\1\342\23\26"+
    "\3\0\1\26\26\0\1\26\5\0\4\26\1\343\23\26"+
    "\3\0\1\26\26\0\1\26\5\0\13\26\1\344\14\26"+
    "\3\0\1\26\26\0\1\26\5\0\10\26\1\345\17\26"+
    "\3\0\1\26\4\0\1\346\37\0\1\340\27\0\1\340"+
    "\31\0\1\347\71\0\1\350\63\0\1\351\13\0\1\352"+
    "\5\0\1\353\77\0\1\354\10\0\2\44\1\0\14\44"+
    "\1\355\5\44\6\355\35\44\5\0\1\274\5\0\1\275"+
    "\61\0\1\275\6\0\1\356\2\0\1\357\67\0\1\360"+
    "\66\0\1\361\51\0\14\212\1\362\6\212\1\0\44\212"+
    "\5\0\1\302\5\0\1\303\61\0\1\303\6\0\1\363"+
    "\2\0\1\364\67\0\1\365\67\0\1\26\5\0\22\26"+
    "\1\366\5\26\3\0\1\26\56\0\1\367\37\0\1\26"+
    "\5\0\20\26\1\370\7\26\3\0\1\26\26\0\1\26"+
    "\5\0\20\26\1\371\7\26\3\0\1\26\54\0\1\372"+
    "\41\0\1\26\5\0\20\26\1\373\7\26\3\0\1\26"+
    "\26\0\1\26\5\0\15\26\1\374\12\26\3\0\1\26"+
    "\26\0\1\26\5\0\24\26\1\375\3\26\3\0\1\26"+
    "\60\0\1\376\35\0\1\26\5\0\10\26\1\377\17\26"+
    "\3\0\1\26\4\0\1\u0100\21\0\1\26\5\0\4\26"+
    "\1\u0101\23\26\3\0\1\26\44\0\1\u0100\27\0\1\u0100"+
    "\33\0\1\u0102\55\0\1\26\5\0\15\26\1\u0103\12\26"+
    "\3\0\1\26\26\0\1\26\5\0\26\26\1\u0104\1\26"+
    "\3\0\1\26\62\0\1\u0105\33\0\1\26\1\u0106\4\0"+
    "\30\26\3\0\1\26\26\0\1\26\5\0\16\26\1\u0107"+
    "\11\26\3\0\1\26\52\0\1\u0108\43\0\1\26\5\0"+
    "\17\26\1\u0109\10\26\3\0\1\26\53\0\1\u010a\67\0"+
    "\1\u010b\42\0\1\26\5\0\21\26\1\u010c\6\26\3\0"+
    "\1\26\5\0\1\u010d\47\0\1\u010d\17\0\1\u010d\20\0"+
    "\1\26\5\0\16\26\1\u010e\11\26\3\0\1\26\52\0"+
    "\1\u010f\43\0\1\26\5\0\2\26\1\u0110\17\26\1\u0111"+
    "\5\26\3\0\1\26\14\0\1\u0112\11\0\1\26\5\0"+
    "\30\26\3\0\1\26\26\0\1\26\5\0\2\26\1\u0113"+
    "\25\26\3\0\1\26\36\0\1\u0114\67\0\1\u0115\17\0"+
    "\1\u0116\50\0\1\354\74\0\1\u0117\27\0\1\u0117\27\0"+
    "\1\u0118\62\0\1\u0119\47\0\2\44\1\0\14\44\1\u011a"+
    "\5\44\6\u011a\35\44\17\0\1\357\55\0\1\u011b\4\0"+
    "\1\u011c\2\0\1\u011d\1\0\1\357\55\0\1\274\5\0"+
    "\1\275\3\0\1\360\67\0\1\u011e\50\0\14\212\1\362"+
    "\6\212\1\4\44\212\17\0\1\364\55\0\1\u011f\7\0"+
    "\1\u0120\1\0\1\364\3\0\1\u0121\51\0\1\302\5\0"+
    "\1\303\3\0\1\365\67\0\1\26\5\0\1\u0122\27\26"+
    "\3\0\1\26\34\0\1\u0123\61\0\1\26\1\u0124\4\0"+
    "\30\26\3\0\1\26\26\0\1\26\5\0\16\26\1\u0125"+
    "\11\26\3\0\1\26\52\0\1\u0126\43\0\1\26\5\0"+
    "\22\26\1\u0127\5\26\3\0\1\26\26\0\1\26\5\0"+
    "\4\26\1\u0128\23\26\3\0\1\26\40\0\1\u0129\55\0"+
    "\1\26\5\0\17\26\1\u012a\10\26\3\0\1\26\53\0"+
    "\1\u012b\42\0\1\26\5\0\6\26\1\u012c\21\26\3\0"+
    "\1\26\42\0\1\u012d\53\0\1\26\5\0\22\26\1\u012e"+
    "\5\26\3\0\1\26\26\0\1\26\5\0\15\26\1\u012f"+
    "\12\26\3\0\1\26\51\0\1\u0130\44\0\1\26\5\0"+
    "\13\26\1\u0131\14\26\3\0\1\26\47\0\1\u0132\67\0"+
    "\1\u0133\46\0\1\26\5\0\4\26\1\u0134\23\26\3\0"+
    "\1\26\40\0\1\u0135\55\0\1\26\5\0\15\26\1\u0136"+
    "\12\26\3\0\1\26\51\0\1\u0137\44\0\1\26\5\0"+
    "\10\26\1\u0138\17\26\3\0\1\26\4\0\1\u0139\32\0"+
    "\1\u013a\56\0\1\26\5\0\1\u013b\27\26\3\0\1\26"+
    "\34\0\1\u013c\77\0\1\u0139\27\0\1\u0139\42\0\1\u013d"+
    "\74\0\1\u013e\100\0\1\u013f\16\0\1\u011b\4\0\1\u011c"+
    "\74\0\1\u0140\67\0\1\u0141\55\0\1\u011f\15\0\1\u0121"+
    "\63\0\1\u0142\67\0\1\26\5\0\21\26\1\u0143\6\26"+
    "\3\0\1\26\5\0\1\u0144\47\0\1\u0144\17\0\1\u0144"+
    "\20\0\1\26\5\0\23\26\1\u0145\4\26\3\0\1\26"+
    "\57\0\1\u0146\36\0\1\26\5\0\22\26\1\u0147\5\26"+
    "\3\0\1\26\56\0\1\u0148\37\0\1\26\5\0\1\u0149"+
    "\27\26\3\0\1\26\34\0\1\u014a\61\0\1\26\5\0"+
    "\22\26\1\u014b\5\26\3\0\1\26\56\0\1\u014c\37\0"+
    "\1\26\5\0\4\26\1\u014d\23\26\3\0\1\26\40\0"+
    "\1\u014e\67\0\1\u014f\55\0\1\26\5\0\20\26\1\u0150"+
    "\7\26\3\0\1\26\54\0\1\u0151\41\0\1\26\5\0"+
    "\16\26\1\u0152\11\26\3\0\1\26\2\0\1\u0153\47\0"+
    "\1\u0153\17\0\1\u0153\35\0\1\u0154\55\0\1\26\5\0"+
    "\13\26\1\u0155\14\26\3\0\1\26\47\0\1\u0156\60\0"+
    "\1\354\56\0\1\u0157\54\0\1\u011b\4\0\1\u011c\4\0"+
    "\1\u0140\67\0\1\u0158\55\0\1\u011f\11\0\1\u0142\3\0"+
    "\1\u0121\63\0\1\26\1\u0159\4\0\30\26\3\0\1\26"+
    "\27\0\1\u0159\66\0\1\26\5\0\15\26\1\u015a\12\26"+
    "\3\0\1\26\51\0\1\u015b\44\0\1\26\5\0\10\26"+
    "\1\u015c\17\26\3\0\1\26\4\0\1\u015d\37\0\1\u015d"+
    "\27\0\1\u015d\21\0\1\26\5\0\1\26\1\u015e\26\26"+
    "\3\0\1\26\35\0\1\u015f\60\0\1\26\5\0\1\u0160"+
    "\27\26\3\0\1\26\34\0\1\u0161\61\0\1\26\5\0"+
    "\21\26\1\u0162\6\26\3\0\1\26\5\0\1\u0163\47\0"+
    "\1\u0163\17\0\1\u0163\20\0\1\26\5\0\10\26\1\u0164"+
    "\17\26\3\0\1\26\4\0\1\u0165\37\0\1\u0165\27\0"+
    "\1\u0165\21\0\1\26\5\0\15\26\1\u0166\12\26\3\0"+
    "\1\26\51\0\1\u0167\32\0\1\u0168\101\0\1\u0169\67\0"+
    "\1\u016a\67\0\1\26\5\0\3\26\1\u016b\24\26\3\0"+
    "\1\26\37\0\1\u016c\56\0\1\26\5\0\16\26\1\u016d"+
    "\11\26\3\0\1\26\52\0\1\u016e\43\0\1\26\5\0"+
    "\13\26\1\u016f\14\26\3\0\1\26\47\0\1\u0170\46\0"+
    "\1\26\5\0\13\26\1\u0171\14\26\3\0\1\26\47\0"+
    "\1\u0172\46\0\1\26\1\u0173\4\0\30\26\3\0\1\26"+
    "\27\0\1\u0173\66\0\1\26\5\0\5\26\1\u0174\22\26"+
    "\3\0\1\26\41\0\1\u0175\54\0\1\26\1\u0176\4\0"+
    "\30\26\3\0\1\26\27\0\1\u0176\113\0\1\u0177\1\0"+
    "\1\u0178\17\0\1\u0178\20\0\1\u0169\1\u0119\66\0\1\26"+
    "\5\0\15\26\1\u0179\12\26\3\0\1\26\51\0\1\u017a"+
    "\44\0\1\26\5\0\4\26\1\u017b\23\26\3\0\1\26"+
    "\40\0\1\u017c\103\0\1\u017d\53\0\1\u017e\55\0\1\26"+
    "\1\u017f\4\0\30\26\3\0\1\26\27\0\1\u017f\66\0"+
    "\1\26\5\0\21\26\1\u0180\6\26\3\0\1\26\5\0"+
    "\1\u0181\47\0\1\u0181\17\0\1\u0181\32\0\1\u0182\65\0"+
    "\1\u0183\57\0\1\26\1\u0184\4\0\30\26\3\0\1\26"+
    "\27\0\1\u0184\102\0\1\u0185\63\0\1\u0186\110\0\1\u0187"+
    "\54\0\1\u0188\27\0\1\u0188\44\0\1\u0189\70\0\1\u018a"+
    "\73\0\1\u018b\62\0\1\u018c\52\0\1\u018d\73\0\1\u018e"+
    "\104\0\1\u018f\17\0\1\u018f\47\0\1\u0190\17\0\1\u0190"+
    "\21\0\1\u0191\67\0\1\u0192\47\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[19040];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\1\1\1\11\2\1\1\11\4\1\2\11"+
    "\16\1\2\11\2\1\1\11\4\1\3\0\1\1\1\11"+
    "\1\0\1\1\3\0\1\11\1\0\16\1\1\0\2\1"+
    "\1\0\5\1\1\0\4\1\4\0\2\1\3\0\1\1"+
    "\6\0\1\1\1\0\7\1\1\0\7\1\1\0\2\1"+
    "\1\0\6\1\1\0\4\1\5\0\1\1\11\0\1\1"+
    "\1\0\2\1\1\0\4\1\1\0\2\1\2\0\3\1"+
    "\1\0\4\1\1\0\1\1\1\11\2\1\1\0\2\1"+
    "\1\0\4\1\1\11\4\1\5\0\1\1\4\0\1\11"+
    "\4\0\1\1\1\0\2\1\1\0\4\1\1\0\2\1"+
    "\2\0\2\1\1\0\1\1\1\11\1\1\1\0\1\1"+
    "\2\0\1\1\1\0\1\1\1\0\5\1\2\0\1\11"+
    "\4\0\1\1\10\0\1\1\1\0\2\1\1\0\3\1"+
    "\1\0\1\1\1\0\1\1\1\0\2\1\2\11\1\1"+
    "\1\0\1\1\2\0\1\1\1\0\1\1\1\0\2\1"+
    "\1\0\1\1\2\0\1\11\3\0\1\1\1\0\1\11"+
    "\4\0\1\11\1\1\1\0\1\11\1\1\1\0\2\1"+
    "\1\11\1\1\1\0\1\1\1\0\2\1\1\0\1\1"+
    "\2\0\1\1\1\0\1\1\1\11\1\1\2\0\1\1"+
    "\3\0\1\11\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\2\1"+
    "\1\0\1\1\1\0\1\1\2\0\1\1\1\11\1\0"+
    "\1\1\1\11\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\3\0"+
    "\1\11\1\1\1\11\1\1\1\0\1\1\1\0\1\1"+
    "\2\11\1\1\2\11\2\0\1\1\1\0\1\1\3\0"+
    "\1\11\1\1\3\0\1\11\14\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[402];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private List<ErroresDeAnalizadores> errores = new ArrayList<>();

    public List<ErroresDeAnalizadores> getErrores() {
        return errores;
    }

    private Symbol symbol(int tipo) {
        return new Symbol(tipo, yyline + 1, yycolumn + 1);
    }

    private Symbol symbol(int tipo, Object valor) {
        return new Symbol(tipo, yyline + 1, yycolumn + 1, valor);
    }

    private void agregarError(String lexema) {
        errores.add(new ErroresDeAnalizadores(
            lexema,
            "Léxico",
            "PKM",
            "Token no válido",
            yyline + 1,
            yycolumn + 1
        ));
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerPKM(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case DENTRO_CADENA: {
              agregarError("Cadena no cerrada");
        return symbol(sym.EOF);
            }  // fall though
            case 403: break;
            default:
          {     return new Symbol(symPKM.EOF, yyline + 1, yycolumn + 1, "EOF");
 }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { agregarError(yytext());
            }
          // fall through
          case 55: break;
          case 2:
            { 
            }
          // fall through
          case 56: break;
          case 3:
            { yybegin(DENTRO_CADENA); return symbol(symPKM.COMILLA);
            }
          // fall through
          case 57: break;
          case 4:
            { return symbol(symPKM.COMA);
            }
          // fall through
          case 58: break;
          case 5:
            { return symbol(symPKM.NUMERO, Double.parseDouble(yytext()));
            }
          // fall through
          case 59: break;
          case 6:
            { return symbol(symPKM.MENOR);
            }
          // fall through
          case 60: break;
          case 7:
            { return symbol(symPKM.IGUAL);
            }
          // fall through
          case 61: break;
          case 8:
            { return symbol(symPKM.MAYOR);
            }
          // fall through
          case 62: break;
          case 9:
            { return symbol(symPKM.IDENTIFICADOR, yytext());
            }
          // fall through
          case 63: break;
          case 10:
            { return symbol(symPKM.LLAVE_ABRE);
            }
          // fall through
          case 64: break;
          case 11:
            { return symbol(symPKM.LLAVE_CIERRA);
            }
          // fall through
          case 65: break;
          case 12:
            { return symbol(symPKM.TEXTO, yytext());
            }
          // fall through
          case 66: break;
          case 13:
            { yybegin(YYINITIAL); return symbol(symPKM.COMILLA);
            }
          // fall through
          case 67: break;
          case 14:
            { return symbol(symPKM.AUTO_CIERRE);
            }
          // fall through
          case 68: break;
          case 15:
            { return symbol(symPKM.CIERRE_ETIQUETA);
            }
          // fall through
          case 69: break;
          case 16:
            { return symbol(symPKM.METADATA_SEP);
            }
          // fall through
          case 70: break;
          case 17:
            { return symbol(symPKM.DROP);
            }
          // fall through
          case 71: break;
          case 18:
            { return symbol(symPKM.FONT);
            }
          // fall through
          case 72: break;
          case 19:
            { return symbol(symPKM.LINE);
            }
          // fall through
          case 73: break;
          case 20:
            { return symbol(symPKM.MONO);
            }
          // fall through
          case 74: break;
          case 21:
            { return symbol(symPKM.OPEN);
            }
          // fall through
          case 75: break;
          case 22:
            { return symbol(symPKM.SIZE);
            }
          // fall through
          case 76: break;
          case 23:
            { return symbol(symPKM.TEXT);
            }
          // fall through
          case 77: break;
          case 24:
            { return symbol(symPKM.VALOR_HORA, yytext());
            }
          // fall through
          case 78: break;
          case 25:
            { return symbol(symPKM.COLOR);
            }
          // fall through
          case 79: break;
          case 26:
            { return symbol(symPKM.HORA);
            }
          // fall through
          case 80: break;
          case 27:
            { return symbol(symPKM.STYLE);
            }
          // fall through
          case 81: break;
          case 28:
            { return symbol(symPKM.TABLE);
            }
          // fall through
          case 82: break;
          case 29:
            { return symbol(symPKM.BORDER);
            }
          // fall through
          case 83: break;
          case 30:
            { return symbol(symPKM.FAMILY);
            }
          // fall through
          case 84: break;
          case 31:
            { return symbol(symPKM.FECHA);
            }
          // fall through
          case 85: break;
          case 32:
            { return symbol(symPKM.SELECT);
            }
          // fall through
          case 86: break;
          case 33:
            { return symbol(symPKM.COLORHEX, yytext());
            }
          // fall through
          case 87: break;
          case 34:
            { return symbol(symPKM.COLORRGB, yytext());
            }
          // fall through
          case 88: break;
          case 35:
            { return symbol(symPKM.COLORHSL, yytext());
            }
          // fall through
          case 89: break;
          case 36:
            { return symbol(symPKM.AUTHOR);
            }
          // fall through
          case 90: break;
          case 37:
            { return symbol(symPKM.CONTENT);
            }
          // fall through
          case 91: break;
          case 38:
            { return symbol(symPKM.CURSIVE);
            }
          // fall through
          case 92: break;
          case 39:
            { return symbol(symPKM.ELEMENT);
            }
          // fall through
          case 93: break;
          case 40:
            { return symbol(symPKM.SECTION);
            }
          // fall through
          case 94: break;
          case 41:
            { return symbol(symPKM.EMOJI, yytext());
            }
          // fall through
          case 95: break;
          case 42:
            { return symbol(symPKM.VALOR_FECHA, yytext());
            }
          // fall through
          case 96: break;
          case 43:
            { return symbol(symPKM.MULTIPLE);
            }
          // fall through
          case 97: break;
          case 44:
            { return symbol(symPKM.VERTICAL);
            }
          // fall through
          case 98: break;
          case 45:
            { return symbol(symPKM.ABIERTAS);
            }
          // fall through
          case 99: break;
          case 46:
            { return symbol(symPKM.BACKGROUND);
            }
          // fall through
          case 100: break;
          case 47:
            { return symbol(symPKM.HORIZONTAL);
            }
          // fall through
          case 101: break;
          case 48:
            { return symbol(symPKM.MULTIPLES);
            }
          // fall through
          case 102: break;
          case 49:
            { return symbol(symPKM.SANS_SERIF);
            }
          // fall through
          case 103: break;
          case 50:
            { return symbol(symPKM.SELECCION);
            }
          // fall through
          case 104: break;
          case 51:
            { return symbol(symPKM.DESCRIPTION);
            }
          // fall through
          case 105: break;
          case 52:
            { return symbol(symPKM.DESPLEGABLES);
            }
          // fall through
          case 106: break;
          case 53:
            { return symbol(symPKM.TOTAL_PREGUNTAS);
            }
          // fall through
          case 107: break;
          case 54:
            { return symbol(symPKM.TOTAL_SECCIONES);
            }
          // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
