// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer1.jflex

package lexer;
//import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;
import pruebasintacticocompi.pruebasproyecto1.Error;


@SuppressWarnings("fallthrough")
public class AnalizadorLexicoCF {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\3\22\1\23"+
    "\6\22\1\24\1\25\1\26\1\27\1\30\1\0\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\1\61"+
    "\1\62\1\63\1\64\1\65\1\66\1\67\1\70\1\0"+
    "\1\71\1\72\1\73\1\74\1\75\1\76\1\77\1\100"+
    "\1\101\2\43\1\102\1\103\1\104\1\105\1\106\1\43"+
    "\1\107\1\110\1\111\1\112\5\43\1\113\1\114\1\115"+
    "\1\116\6\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\1\1\2\1\3\1\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\1\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\1\23\21\1\22"+
    "\1\23\1\24\3\21\1\25\1\1\1\26\1\27\1\30"+
    "\1\0\1\31\2\0\1\32\1\0\1\33\3\0\1\34"+
    "\1\35\1\36\1\0\2\21\1\37\5\21\1\40\15\21"+
    "\1\41\3\21\1\42\3\0\1\43\3\0\7\21\1\44"+
    "\7\21\1\45\3\21\1\46\7\21\2\0\1\2\11\0"+
    "\1\21\1\47\4\21\1\50\2\21\1\51\1\52\6\21"+
    "\1\53\7\21\3\0\1\54\1\55\7\0\1\56\1\57"+
    "\1\60\4\21\1\61\10\21\1\62\1\63\4\21\11\0"+
    "\1\21\1\64\1\65\4\21\1\66\4\21\1\67\1\70"+
    "\1\21\1\71\1\72\1\73\1\74\1\75\5\0\1\76"+
    "\5\21\1\77\2\21\1\100\5\0\6\21\1\101\4\0"+
    "\1\102\6\21\2\0\1\21\1\103\2\21\1\104\1\21"+
    "\1\0\10\21\1\105\1\21\1\106\4\21\1\107\1\21"+
    "\1\110";

  private static int [] zzUnpackAction() {
    int [] result = new int[294];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\117\0\236\0\355\0\u013c\0\u018b\0\u01da\0\117"+
    "\0\u0229\0\u0278\0\117\0\117\0\117\0\117\0\117\0\u02c7"+
    "\0\u0316\0\u0365\0\117\0\117\0\u03b4\0\u0403\0\u0452\0\u04a1"+
    "\0\u04f0\0\u053f\0\u058e\0\u05dd\0\u062c\0\u067b\0\u06ca\0\u0719"+
    "\0\u0768\0\u07b7\0\u0806\0\u0855\0\u08a4\0\u08f3\0\u0942\0\u0991"+
    "\0\u09e0\0\u0a2f\0\u0a7e\0\117\0\117\0\117\0\u0acd\0\u0b1c"+
    "\0\u0b6b\0\117\0\u0bba\0\117\0\117\0\117\0\u013c\0\117"+
    "\0\u0c09\0\u0c58\0\117\0\u0ca7\0\117\0\u0cf6\0\u0d45\0\u0d94"+
    "\0\117\0\117\0\117\0\u0de3\0\u0e32\0\u0e81\0\u0ed0\0\u0f1f"+
    "\0\u0f6e\0\u0fbd\0\u100c\0\u105b\0\u04f0\0\u10aa\0\u10f9\0\u1148"+
    "\0\u1197\0\u11e6\0\u1235\0\u1284\0\u12d3\0\u1322\0\u1371\0\u13c0"+
    "\0\u140f\0\u145e\0\u04f0\0\u14ad\0\u14fc\0\u154b\0\117\0\u159a"+
    "\0\u15e9\0\u1638\0\u0d45\0\u1687\0\u16d6\0\u1725\0\u1774\0\u17c3"+
    "\0\u1812\0\u1861\0\u18b0\0\u18ff\0\u194e\0\u04f0\0\u199d\0\u19ec"+
    "\0\u1a3b\0\u1a8a\0\u1ad9\0\u1b28\0\u1b77\0\u04f0\0\u1bc6\0\u1c15"+
    "\0\u1c64\0\u04f0\0\u1cb3\0\u1d02\0\u1d51\0\u1da0\0\u1def\0\u1e3e"+
    "\0\u1e8d\0\u1edc\0\u1f2b\0\117\0\u1f7a\0\u1fc9\0\u2018\0\u2067"+
    "\0\u20b6\0\u2105\0\u2154\0\u21a3\0\u21f2\0\u2241\0\u04f0\0\u2290"+
    "\0\u22df\0\u232e\0\u237d\0\u04f0\0\u23cc\0\u241b\0\u04f0\0\u04f0"+
    "\0\u246a\0\u24b9\0\u2508\0\u2557\0\u25a6\0\u25f5\0\u04f0\0\u2644"+
    "\0\u2693\0\u26e2\0\u2731\0\u2780\0\u27cf\0\u281e\0\u286d\0\u28bc"+
    "\0\u290b\0\117\0\117\0\u295a\0\u29a9\0\u29f8\0\u2a47\0\u2a96"+
    "\0\u2ae5\0\u2b34\0\117\0\117\0\u04f0\0\u2b83\0\u2bd2\0\u2c21"+
    "\0\u2c70\0\u04f0\0\u2cbf\0\u2d0e\0\u2d5d\0\u2dac\0\u2dfb\0\u2e4a"+
    "\0\u2e99\0\u2ee8\0\u04f0\0\u04f0\0\u2f37\0\u2f86\0\u2fd5\0\u3024"+
    "\0\u3073\0\u30c2\0\u3111\0\u3160\0\u31af\0\u31fe\0\u324d\0\u329c"+
    "\0\u32eb\0\u333a\0\u04f0\0\u04f0\0\u3389\0\u33d8\0\u3427\0\u3476"+
    "\0\u04f0\0\u34c5\0\u3514\0\u3563\0\u35b2\0\u04f0\0\u04f0\0\u3601"+
    "\0\u04f0\0\117\0\117\0\117\0\117\0\u3650\0\u369f\0\u36ee"+
    "\0\u373d\0\u378c\0\u04f0\0\u37db\0\u382a\0\u3879\0\u38c8\0\u3917"+
    "\0\u04f0\0\u3966\0\u39b5\0\u04f0\0\u3a04\0\u3a53\0\u3aa2\0\u3af1"+
    "\0\u3b40\0\u3b8f\0\u3bde\0\u3c2d\0\u3c7c\0\u3ccb\0\u3d1a\0\u04f0"+
    "\0\u3d69\0\u3db8\0\u3e07\0\u3e56\0\117\0\u3ea5\0\u3ef4\0\u3f43"+
    "\0\u3f92\0\u3fe1\0\u4030\0\u407f\0\u40ce\0\u411d\0\u04f0\0\u416c"+
    "\0\u41bb\0\u04f0\0\u420a\0\u4259\0\u42a8\0\u42f7\0\u4346\0\u4395"+
    "\0\u43e4\0\u4433\0\u4482\0\u44d1\0\u04f0\0\u4520\0\u04f0\0\u456f"+
    "\0\u45be\0\u460d\0\u465c\0\u04f0\0\u46ab\0\u04f0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[294];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\2\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\2\31\1\42\1\43\1\31\1\44\1\45\1\31"+
    "\1\46\1\47\1\50\1\31\1\51\1\52\1\31\1\53"+
    "\1\31\1\54\1\2\1\55\1\56\1\2\10\31\1\57"+
    "\2\31\1\60\3\31\1\61\2\31\1\62\1\63\1\64"+
    "\1\65\120\0\2\3\120\0\1\66\112\0\5\67\1\70"+
    "\57\67\1\71\31\67\22\0\2\72\6\0\6\72\31\0"+
    "\6\72\20\0\2\7\2\0\113\7\11\0\1\73\127\0"+
    "\2\74\113\0\1\75\112\0\1\76\122\0\1\77\1\0"+
    "\2\22\115\0\2\100\3\0\1\101\116\0\1\102\116\0"+
    "\1\103\153\0\1\104\54\0\2\31\6\0\32\31\4\0"+
    "\23\31\26\0\2\31\6\0\13\31\1\105\16\31\4\0"+
    "\23\31\26\0\2\31\6\0\24\31\1\106\5\31\4\0"+
    "\23\31\26\0\2\31\6\0\16\31\1\107\2\31\1\110"+
    "\10\31\4\0\23\31\26\0\2\31\6\0\13\31\1\111"+
    "\16\31\4\0\23\31\26\0\2\31\6\0\16\31\1\112"+
    "\13\31\4\0\23\31\26\0\2\31\6\0\21\31\1\113"+
    "\10\31\4\0\23\31\26\0\2\31\6\0\16\31\1\114"+
    "\13\31\4\0\23\31\26\0\2\31\6\0\5\31\1\115"+
    "\24\31\4\0\23\31\26\0\2\31\6\0\10\31\1\116"+
    "\21\31\4\0\23\31\26\0\2\31\6\0\16\31\1\117"+
    "\5\31\1\120\5\31\4\0\23\31\26\0\2\31\6\0"+
    "\17\31\1\121\12\31\4\0\23\31\26\0\2\31\6\0"+
    "\24\31\1\122\5\31\4\0\23\31\26\0\2\31\6\0"+
    "\4\31\1\123\25\31\4\0\23\31\26\0\2\31\6\0"+
    "\1\124\3\31\1\125\5\31\1\126\17\31\4\0\23\31"+
    "\26\0\2\31\6\0\4\31\1\127\25\31\4\0\23\31"+
    "\26\0\2\31\6\0\4\31\1\130\25\31\4\0\23\31"+
    "\26\0\2\31\6\0\7\31\1\131\22\31\4\0\23\31"+
    "\26\0\2\31\6\0\4\31\1\132\25\31\4\0\23\31"+
    "\26\0\2\31\6\0\32\31\4\0\14\31\1\133\6\31"+
    "\26\0\2\31\6\0\32\31\4\0\22\31\1\134\26\0"+
    "\2\31\6\0\32\31\4\0\16\31\1\135\2\31\1\136"+
    "\1\31\120\0\1\137\2\0\2\67\2\0\113\67\22\0"+
    "\2\140\6\0\6\140\31\0\6\140\36\0\1\141\3\0"+
    "\2\74\73\0\14\76\1\142\102\76\22\0\2\143\111\0"+
    "\1\144\3\0\2\100\117\0\1\145\1\0\1\146\112\0"+
    "\2\31\6\0\1\147\23\31\1\150\5\31\4\0\23\31"+
    "\26\0\2\31\6\0\21\31\1\151\10\31\4\0\23\31"+
    "\26\0\2\31\6\0\23\31\1\152\1\153\5\31\4\0"+
    "\23\31\26\0\2\31\6\0\16\31\1\154\13\31\4\0"+
    "\23\31\26\0\2\31\6\0\22\31\1\155\7\31\4\0"+
    "\23\31\26\0\2\31\6\0\21\31\1\156\10\31\4\0"+
    "\23\31\26\0\2\31\6\0\4\31\1\157\25\31\4\0"+
    "\23\31\26\0\2\31\6\0\21\31\1\160\10\31\4\0"+
    "\23\31\26\0\2\31\6\0\15\31\1\161\14\31\4\0"+
    "\23\31\26\0\2\31\6\0\15\31\1\162\14\31\4\0"+
    "\23\31\26\0\2\31\6\0\13\31\1\163\16\31\4\0"+
    "\23\31\26\0\2\31\6\0\4\31\1\164\25\31\4\0"+
    "\23\31\26\0\2\31\6\0\21\31\1\165\10\31\4\0"+
    "\23\31\26\0\2\31\6\0\3\31\1\166\26\31\4\0"+
    "\23\31\26\0\2\31\6\0\15\31\1\167\14\31\4\0"+
    "\23\31\26\0\2\31\6\0\2\31\1\170\10\31\1\171"+
    "\16\31\4\0\23\31\26\0\2\31\6\0\30\31\1\172"+
    "\1\31\4\0\23\31\26\0\2\31\6\0\27\31\1\173"+
    "\2\31\4\0\23\31\26\0\2\31\6\0\21\31\1\174"+
    "\10\31\4\0\23\31\26\0\2\31\6\0\10\31\1\175"+
    "\21\31\4\0\23\31\26\0\2\31\6\0\13\31\1\176"+
    "\16\31\4\0\23\31\26\0\2\31\6\0\32\31\4\0"+
    "\13\31\1\177\7\31\26\0\2\31\6\0\32\31\4\0"+
    "\5\31\1\200\15\31\26\0\2\31\6\0\32\31\4\0"+
    "\17\31\1\201\3\31\26\0\2\202\6\0\6\202\31\0"+
    "\6\202\42\0\2\203\73\0\14\76\1\142\4\76\1\204"+
    "\75\76\22\0\2\205\105\0\1\206\1\207\53\0\1\210"+
    "\3\0\1\211\4\0\1\212\7\0\1\213\3\0\1\214"+
    "\25\0\1\215\2\0\1\146\112\0\2\31\6\0\2\31"+
    "\1\216\27\31\4\0\23\31\26\0\2\31\6\0\4\31"+
    "\1\217\25\31\4\0\23\31\26\0\2\31\6\0\22\31"+
    "\1\220\7\31\4\0\23\31\26\0\2\31\6\0\23\31"+
    "\1\221\6\31\4\0\23\31\26\0\2\31\6\0\1\31"+
    "\1\222\30\31\4\0\23\31\26\0\2\31\6\0\17\31"+
    "\1\223\12\31\4\0\23\31\26\0\2\31\6\0\4\31"+
    "\1\224\25\31\4\0\23\31\26\0\2\31\6\0\4\31"+
    "\1\225\25\31\4\0\23\31\26\0\2\31\6\0\10\31"+
    "\1\226\21\31\4\0\23\31\26\0\2\31\6\0\4\31"+
    "\1\227\25\31\4\0\23\31\26\0\2\31\6\0\16\31"+
    "\1\230\13\31\4\0\23\31\26\0\2\31\6\0\23\31"+
    "\1\231\6\31\4\0\23\31\26\0\2\31\6\0\15\31"+
    "\1\232\14\31\4\0\23\31\26\0\2\31\6\0\17\31"+
    "\1\233\12\31\4\0\23\31\26\0\2\31\6\0\22\31"+
    "\1\234\7\31\4\0\23\31\26\0\2\31\6\0\23\31"+
    "\1\235\6\31\4\0\23\31\26\0\2\31\6\0\4\31"+
    "\1\236\25\31\4\0\23\31\26\0\2\31\6\0\23\31"+
    "\1\237\6\31\4\0\23\31\26\0\2\31\6\0\23\31"+
    "\1\240\6\31\4\0\23\31\26\0\2\31\6\0\13\31"+
    "\1\241\7\31\1\242\6\31\4\0\23\31\26\0\2\31"+
    "\6\0\13\31\1\243\16\31\4\0\23\31\26\0\2\31"+
    "\6\0\32\31\4\0\2\31\1\244\20\31\26\0\2\31"+
    "\6\0\32\31\4\0\3\31\1\245\17\31\26\0\2\31"+
    "\6\0\32\31\4\0\11\31\1\246\11\31\26\0\2\247"+
    "\6\0\6\247\31\0\6\247\36\0\1\250\3\0\2\203"+
    "\111\0\1\251\3\0\2\205\105\0\1\206\53\0\1\252"+
    "\43\0\1\207\52\0\1\253\117\0\1\254\120\0\1\255"+
    "\122\0\1\256\112\0\1\257\3\0\1\260\5\0\1\261"+
    "\5\0\1\262\73\0\1\263\25\0\1\214\25\0\1\215"+
    "\42\0\1\264\52\0\2\31\6\0\12\31\1\265\17\31"+
    "\4\0\23\31\26\0\2\31\6\0\10\31\1\266\21\31"+
    "\4\0\23\31\26\0\2\31\6\0\4\31\1\267\25\31"+
    "\4\0\23\31\26\0\2\31\6\0\13\31\1\270\16\31"+
    "\4\0\23\31\26\0\2\31\6\0\32\31\4\0\1\271"+
    "\22\31\26\0\2\31\6\0\15\31\1\272\14\31\4\0"+
    "\23\31\26\0\2\31\6\0\31\31\1\273\4\0\23\31"+
    "\26\0\2\31\6\0\10\31\1\274\21\31\4\0\23\31"+
    "\26\0\2\31\6\0\32\31\4\0\1\275\22\31\26\0"+
    "\2\31\6\0\13\31\1\276\16\31\4\0\23\31\26\0"+
    "\2\31\6\0\32\31\4\0\1\277\22\31\26\0\2\31"+
    "\6\0\10\31\1\300\21\31\4\0\23\31\26\0\2\31"+
    "\6\0\2\31\1\301\27\31\4\0\23\31\26\0\2\31"+
    "\6\0\10\31\1\302\21\31\4\0\23\31\26\0\2\31"+
    "\6\0\4\31\1\303\25\31\4\0\23\31\26\0\2\31"+
    "\6\0\4\31\1\304\25\31\4\0\23\31\26\0\2\31"+
    "\6\0\16\31\1\305\13\31\4\0\23\31\26\0\2\31"+
    "\6\0\32\31\4\0\5\31\1\306\15\31\26\0\2\31"+
    "\6\0\32\31\4\0\11\31\1\307\11\31\26\0\2\31"+
    "\6\0\32\31\4\0\14\31\1\310\6\31\26\0\2\311"+
    "\6\0\6\311\31\0\6\311\42\0\2\312\115\0\2\313"+
    "\117\0\1\314\203\0\1\254\76\0\1\315\121\0\1\316"+
    "\131\0\1\317\110\0\1\320\106\0\1\321\47\0\2\31"+
    "\6\0\25\31\1\322\4\31\4\0\23\31\26\0\2\31"+
    "\6\0\3\31\1\323\26\31\4\0\23\31\26\0\2\31"+
    "\6\0\4\31\1\324\25\31\4\0\23\31\26\0\2\31"+
    "\6\0\20\31\1\325\11\31\4\0\23\31\26\0\2\31"+
    "\6\0\16\31\1\326\13\31\4\0\23\31\26\0\2\31"+
    "\6\0\17\31\1\327\12\31\4\0\23\31\26\0\2\31"+
    "\6\0\20\31\1\330\11\31\4\0\23\31\26\0\2\31"+
    "\6\0\4\31\1\331\25\31\4\0\23\31\26\0\2\31"+
    "\6\0\22\31\1\332\7\31\4\0\23\31\26\0\2\31"+
    "\6\0\16\31\1\333\13\31\4\0\23\31\26\0\2\31"+
    "\6\0\23\31\1\334\6\31\4\0\23\31\26\0\2\31"+
    "\6\0\2\31\1\335\27\31\4\0\23\31\26\0\2\31"+
    "\6\0\26\31\1\336\3\31\4\0\23\31\26\0\2\31"+
    "\6\0\32\31\4\0\17\31\1\337\3\31\26\0\2\31"+
    "\6\0\32\31\4\0\1\31\1\340\21\31\26\0\2\31"+
    "\6\0\32\31\4\0\7\31\1\341\13\31\26\0\2\342"+
    "\6\0\6\342\31\0\6\342\33\0\1\343\6\0\2\312"+
    "\115\0\2\313\4\0\1\344\154\0\1\345\137\0\1\346"+
    "\33\0\1\347\173\0\1\350\117\0\1\351\123\0\1\352"+
    "\31\0\2\31\6\0\4\31\1\353\25\31\4\0\23\31"+
    "\26\0\2\31\6\0\24\31\1\354\5\31\4\0\23\31"+
    "\26\0\2\31\6\0\15\31\1\355\14\31\4\0\23\31"+
    "\26\0\2\31\6\0\13\31\1\356\16\31\4\0\23\31"+
    "\26\0\2\31\6\0\24\31\1\357\5\31\4\0\23\31"+
    "\26\0\2\31\6\0\4\31\1\360\25\31\4\0\23\31"+
    "\26\0\2\31\6\0\15\31\1\361\14\31\4\0\23\31"+
    "\26\0\2\31\6\0\32\31\4\0\1\362\22\31\26\0"+
    "\2\31\6\0\1\363\31\31\4\0\23\31\26\0\2\31"+
    "\6\0\32\31\4\0\12\31\1\364\10\31\115\0\1\365"+
    "\73\0\1\252\135\0\1\366\106\0\1\367\40\0\1\370"+
    "\4\0\1\371\114\0\2\31\6\0\4\31\1\372\25\31"+
    "\4\0\23\31\26\0\2\31\6\0\23\31\1\373\6\31"+
    "\4\0\23\31\26\0\2\31\6\0\4\31\1\374\25\31"+
    "\4\0\23\31\26\0\2\31\6\0\4\31\1\375\25\31"+
    "\4\0\23\31\26\0\2\31\6\0\21\31\1\376\10\31"+
    "\4\0\23\31\26\0\2\31\6\0\20\31\1\377\11\31"+
    "\4\0\23\31\26\0\2\31\6\0\13\31\1\u0100\16\31"+
    "\4\0\23\31\30\0\1\u0101\204\0\1\u0102\30\0\1\u0103"+
    "\114\0\2\u0104\115\0\2\u0104\42\0\1\u0105\52\0\2\31"+
    "\6\0\22\31\1\u0106\7\31\4\0\23\31\26\0\2\31"+
    "\6\0\1\u0107\31\31\4\0\23\31\26\0\2\31\6\0"+
    "\32\31\4\0\1\u0108\22\31\26\0\2\31\6\0\22\31"+
    "\1\u0109\7\31\4\0\23\31\26\0\2\31\6\0\10\31"+
    "\1\u010a\21\31\4\0\23\31\26\0\2\31\6\0\24\31"+
    "\1\u010b\5\31\4\0\23\31\72\0\1\264\140\0\1\u010c"+
    "\74\0\1\253\52\0\2\u0104\1\u010d\114\0\2\31\6\0"+
    "\23\31\1\u010e\6\31\4\0\23\31\26\0\2\31\6\0"+
    "\13\31\1\u010f\16\31\4\0\23\31\26\0\2\31\6\0"+
    "\20\31\1\u0110\11\31\4\0\23\31\26\0\2\31\6\0"+
    "\23\31\1\u0111\6\31\4\0\23\31\26\0\2\31\6\0"+
    "\5\31\1\u0112\24\31\4\0\23\31\26\0\2\31\6\0"+
    "\4\31\1\u0113\25\31\4\0\23\31\30\0\1\u0114\160\0"+
    "\1\u0105\52\0\2\31\6\0\10\31\1\u0115\21\31\4\0"+
    "\23\31\26\0\2\31\6\0\24\31\1\u0116\5\31\4\0"+
    "\23\31\26\0\2\31\6\0\10\31\1\u0117\21\31\4\0"+
    "\23\31\26\0\2\31\6\0\22\31\1\u0118\7\31\4\0"+
    "\23\31\72\0\1\263\52\0\2\31\6\0\16\31\1\u0119"+
    "\13\31\4\0\23\31\26\0\2\31\6\0\4\31\1\u011a"+
    "\25\31\4\0\23\31\26\0\2\31\6\0\16\31\1\u011b"+
    "\13\31\4\0\23\31\26\0\2\31\6\0\23\31\1\u011c"+
    "\6\31\4\0\23\31\26\0\2\31\6\0\15\31\1\u011d"+
    "\14\31\4\0\23\31\26\0\2\31\6\0\22\31\1\u011e"+
    "\7\31\4\0\23\31\26\0\2\31\6\0\15\31\1\u011f"+
    "\14\31\4\0\23\31\26\0\2\31\6\0\10\31\1\u0120"+
    "\21\31\4\0\23\31\26\0\2\31\6\0\23\31\1\u0121"+
    "\6\31\4\0\23\31\26\0\2\31\6\0\16\31\1\u0122"+
    "\13\31\4\0\23\31\26\0\2\31\6\0\10\31\1\u0123"+
    "\21\31\4\0\23\31\26\0\2\31\6\0\15\31\1\u0124"+
    "\14\31\4\0\23\31\26\0\2\31\6\0\16\31\1\u0125"+
    "\13\31\4\0\23\31\26\0\2\31\6\0\15\31\1\u0126"+
    "\14\31\4\0\23\31\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[18170];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\2\1\5\11\3\1\2\11"+
    "\27\1\3\11\3\1\1\11\1\1\3\11\1\0\1\11"+
    "\2\0\1\11\1\0\1\11\3\0\3\11\1\0\32\1"+
    "\1\11\3\0\1\1\3\0\33\1\2\0\1\11\11\0"+
    "\31\1\3\0\2\11\7\0\2\11\24\1\11\0\20\1"+
    "\4\11\5\0\12\1\5\0\7\1\4\0\1\11\6\1"+
    "\2\0\6\1\1\0\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[294];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private List<Error> listaDeErrores = new ArrayList();

    public List<Error> getErrores() {
        return listaDeErrores;
    }

    private void agregarError(String lexema) {
        listaDeErrores.add(new Error(lexema,"Lexico", yyline + 1, yycolumn + 1));
    }    



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexicoCF(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return -1;
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { agregarError(yytext());
            }
          // fall through
          case 73: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 74: break;
          case 3:
            { System.out.println("TOKEN: MODULO");
            }
          // fall through
          case 75: break;
          case 4:
            { System.out.println("TOKEN: (");
            }
          // fall through
          case 76: break;
          case 5:
            { System.out.println("TOKEN: )");
            }
          // fall through
          case 77: break;
          case 6:
            { System.out.println("TOKEN: MULTIPLICACION");
            }
          // fall through
          case 78: break;
          case 7:
            { System.out.println("TOKEN: SUMA");
            }
          // fall through
          case 79: break;
          case 8:
            { System.out.println("TOKEN: COMA");
            }
          // fall through
          case 80: break;
          case 9:
            { System.out.println("TOKEN: RESTA");
            }
          // fall through
          case 81: break;
          case 10:
            { System.out.println("TOKEN: DIVISION");
            }
          // fall through
          case 82: break;
          case 11:
            { System.out.println("TOKEN: ENTERO -> " + yytext());
            }
          // fall through
          case 83: break;
          case 12:
            { System.out.println("TOKEN: DOS_PUNTOS");
            }
          // fall through
          case 84: break;
          case 13:
            { System.out.println("TOKEN: PUNTO_COMA");
            }
          // fall through
          case 85: break;
          case 14:
            { System.out.println("TOKEN: MENOR");
            }
          // fall through
          case 86: break;
          case 15:
            { System.out.println("TOKEN: ASIGNACION");
            }
          // fall through
          case 87: break;
          case 16:
            { System.out.println("TOKEN: MAYOR");
            }
          // fall through
          case 88: break;
          case 17:
            { System.out.println("TOKEN: IDENTIFICADOR -> " + yytext());
            }
          // fall through
          case 89: break;
          case 18:
            { System.out.println("TOKEN: [");
            }
          // fall through
          case 90: break;
          case 19:
            { System.out.println("TOKEN: ]");
            }
          // fall through
          case 91: break;
          case 20:
            { System.out.println("TOKEN: POTENCIA");
            }
          // fall through
          case 92: break;
          case 21:
            { System.out.println("TOKEN: {");
            }
          // fall through
          case 93: break;
          case 22:
            { System.out.println("TOKEN: }");
            }
          // fall through
          case 94: break;
          case 23:
            { System.out.println("TOKEN: NOT");
            }
          // fall through
          case 95: break;
          case 24:
            { System.out.println("TOKEN: DIFERENTE");
            }
          // fall through
          case 96: break;
          case 25:
            { System.out.println("TOKEN: STRING -> " + yytext());
            }
          // fall through
          case 97: break;
          case 26:
            { System.out.println("TOKEN: AND");
            }
          // fall through
          case 98: break;
          case 27:
            { System.out.println("TOKEN: RANGO");
            }
          // fall through
          case 99: break;
          case 28:
            { System.out.println("TOKEN: MENOR_IGUAL");
            }
          // fall through
          case 100: break;
          case 29:
            { System.out.println("TOKEN: IGUAL");
            }
          // fall through
          case 101: break;
          case 30:
            { System.out.println("TOKEN: MAYOR_IGUAL");
            }
          // fall through
          case 102: break;
          case 31:
            { System.out.println("TOKEN: DO");
            }
          // fall through
          case 103: break;
          case 32:
            { System.out.println("TOKEN: IF");
            }
          // fall through
          case 104: break;
          case 33:
            { System.out.println("TOKEN: IN");
            }
          // fall through
          case 105: break;
          case 34:
            { System.out.println("TOKEN: OR");
            }
          // fall through
          case 106: break;
          case 35:
            { System.out.println("TOKEN: DECIMAL -> " + yytext());
            }
          // fall through
          case 107: break;
          case 36:
            { System.out.println("TOKEN: FOR");
            }
          // fall through
          case 108: break;
          case 37:
            { System.out.println("TOKEN: COLOR_RED");
            }
          // fall through
          case 109: break;
          case 38:
            { System.out.println("TOKEN: COLOR_SKY");
            }
          // fall through
          case 110: break;
          case 39:
            { System.out.println("TOKEN: COLOR_BLUE");
            }
          // fall through
          case 111: break;
          case 40:
            { System.out.println("TOKEN: ELSE");
            }
          // fall through
          case 112: break;
          case 41:
            { System.out.println("TOKEN: LINE");
            }
          // fall through
          case 113: break;
          case 42:
            { System.out.println("TOKEN: MONO");
            }
          // fall through
          case 114: break;
          case 43:
            { System.out.println("TOKEN: TEXT");
            }
          // fall through
          case 115: break;
          case 44:
            { System.out.println("EMOJI: 😢");
            }
          // fall through
          case 116: break;
          case 45:
            { System.out.println("EMOJI: 😊");
            }
          // fall through
          case 117: break;
          case 46:
            { System.out.println("EMOJI: 😐");
            }
          // fall through
          case 118: break;
          case 47:
            { System.out.println("EMOJI: ❤️");
            }
          // fall through
          case 119: break;
          case 48:
            { System.out.println("TOKEN: COLOR_BLACK");
            }
          // fall through
          case 120: break;
          case 49:
            { System.out.println("TOKEN: COLOR_GREEN");
            }
          // fall through
          case 121: break;
          case 50:
            { System.out.println("TOKEN: WHILE");
            }
          // fall through
          case 122: break;
          case 51:
            { System.out.println("TOKEN: COLOR_WHITE");
            }
          // fall through
          case 123: break;
          case 52:
            { System.out.println("TOKEN: DOTTED");
            }
          // fall through
          case 124: break;
          case 53:
            { System.out.println("TOKEN: DOUBLE");
            }
          // fall through
          case 125: break;
          case 54:
            { System.out.println("TOKEN: COLOR_PURPLE");
            }
          // fall through
          case 126: break;
          case 55:
            { System.out.println("TOKEN: COLOR_YELLOW");
            }
          // fall through
          case 127: break;
          case 56:
            { System.out.println("TOKEN: NUMBER_TYPE");
            }
          // fall through
          case 128: break;
          case 57:
            { System.out.println("TOKEN: STRING_TYPE");
            }
          // fall through
          case 129: break;
          case 58:
            { System.out.println("TOKEN: COLOR_HEX -> " + yytext());
            }
          // fall through
          case 130: break;
          case 59:
            { System.out.println("TOKEN: COLOR_RGB -> " + yytext());
            }
          // fall through
          case 131: break;
          case 60:
            { System.out.println("TOKEN: COLOR_HSL -> " + yytext());
            }
          // fall through
          case 132: break;
          case 61:
            { System.out.println("EMOJI: 🐱");
            }
          // fall through
          case 133: break;
          case 62:
            { System.out.println("TOKEN: CURSIVE");
            }
          // fall through
          case 134: break;
          case 63:
            { System.out.println("TOKEN: SECTION");
            }
          // fall through
          case 135: break;
          case 64:
            { System.out.println("TOKEN: SPECIAL_TYPE");
            }
          // fall through
          case 136: break;
          case 65:
            { System.out.println("TOKEN: VERTICAL");
            }
          // fall through
          case 137: break;
          case 66:
            { System.out.println("EMOJI: ⭐");
            }
          // fall through
          case 138: break;
          case 67:
            { System.out.println("TOKEN: HORIZONTAL");
            }
          // fall through
          case 139: break;
          case 68:
            { System.out.println("TOKEN: SANS_SERIF");
            }
          // fall through
          case 140: break;
          case 69:
            { System.out.println("TOKEN: DROP_QUESTION");
            }
          // fall through
          case 141: break;
          case 70:
            { System.out.println("TOKEN: OPEN_QUESTION");
            }
          // fall through
          case 142: break;
          case 71:
            { System.out.println("TOKEN: SELECT_QUESTION");
            }
          // fall through
          case 143: break;
          case 72:
            { System.out.println("TOKEN: MULTIPLE_QUESTION");
            }
          // fall through
          case 144: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
